# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr.shape

(3,)

In [10]:
arr_2d.shape

(3, 3)

## II. Numpy로 연산하기

###Vector와 Scalar 사이의 연산
벡터의 각 원소에 대해서 연산을 진행

In [12]:
x=np.array([1,2,3])
c=5
print("더하기 : {}".format(x+c))
print("빼기 : {}".format(x-c))
print("곱하기 : {}".format(x*c))
print("나누기 : {}".format(x/c))


더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


###Vector와 Vector 사이의 연산
벡터의 같은 인덱스끼리 연산이 진행

In [13]:
y=np.array([1,3,5])
z=np.array([2,9,20])

print("더하기 : {}".format(y+z))
print("빼기 : {}".format(y-z))
print("곱하기 : {}".format(y*z))
print("나누기 : {}".format(y/z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


###Array Indexing
python의 리스트와 유사하게 진행

In [14]:
w=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
w[0,0]

1

In [15]:
w[2,3]

12

In [16]:
#7을 가져오려면?
w[1,2]

7

###Array Slicing
python의 리스트와 유사하게 진행

In [19]:
w[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [17]:
w[0:2,0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
w[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
w[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
w[0:3,]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
w[0:3,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [23]:
w[:,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

###Array Broadcasting
기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능     
하지만 만약에 피연산자가 연산 가능하도록 변환이 가능하다면 연산이 가능    
이를 **broadcasting**이라고 함

###1.M by N, M by 1

In [25]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
x=np.array([0,1,0])

x=x[:,None] #x를 전치
print(x)
print(a+x)

[[0]
 [1]
 [0]]
[[1 2 3]
 [5 6 7]
 [7 8 9]]


###2.M by N, 1 by N

In [26]:
y=np.array([0,1,-1])
print(a*y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


###3.M by 1, 1 by N

In [28]:
t=np.array([1,2,3]) #열벡터로 바꿔줘야함
t=t[:,None] #Transpose

u=np.array([2,0,-2])

print(t+u)
'''
1 1 1   2 0 -2
2 2 2 + 2 0 -2
3 3 3   2 0 -2
'''

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


'\n1 1 1   2 0 -2\n2 2 2 + 2 0 -2\n3 3 3   2 0 -2\n'

## III. Numpy로 선형대수 지식 끼얹기



##A.basis
###영벡터(행렬)


*   원소가 모두 0인 벡터(행렬)
*   np.zeros(dim)을 통해 생성, dim은 값, 혹은 튜플(,)



In [29]:
np.zeros(1)

array([0.])

In [30]:
np.zeros(3)

array([0., 0., 0.])

In [31]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

###일벡터(행렬)


*   원소가 모두 1인 벡터(행렬)
*   np.ones(dim)을 통해 생성, dim은 값, 튜플(,)



In [32]:
np.ones(2)

array([1., 1.])

In [33]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

###대각행렬


*   Main Diagonal을 제외한 성분이 0인 행렬
*   np.diag((main_diagonals))을 통해 생성할 수 있음



In [34]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [35]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

###항등행렬

*   main diagonal==1인 diagonal matrix(대각 행렬)
*   np.eye(n,(dtype=int,uint,float, complex, ...))를 사용



In [36]:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 ###행렬곱


*   행렬 간에 정의되는 곱 연산(dot product)
*   np.dot(), @를 사용



In [38]:
mat_1=np.array([[1,4],[2,3]])
mat_2=np.array([[7,9],[0,6]])

mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

In [39]:
mat_1@mat_2

array([[ 7, 33],
       [14, 36]])

##B. Furthermore
###트레이스


*   Main Diagonal의 Sum
*   np.trace()을 사용




In [40]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr.trace()

15

In [42]:
np.eye(2, dtype=int).trace()

2

###행렬식


*   행렬을 대표하는 값 중 하나
*   선형변환 과정에서 Vector의 Scailing 척도
*   np.linalg.det()으로 계산



In [43]:
arr_2=np.array([[2,3],[1,6]])
arr_2

array([[2, 3],
       [1, 6]])

In [44]:
np.linalg.det(arr_2)

9.000000000000002

In [45]:
arr_3=np.array([[1,4,7],[2,5,8],[3,6,9]])
arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [46]:
np.linalg.det(arr_3)

0.0

###역행렬


*   행렬 A에 대해서 AB=BA=I를 만족하는 행렬 B
*   np.linalg.inv()을 사용



In [47]:
mat=np.array([[1,4],[2,3]])
mat

array([[1, 4],
       [2, 3]])

In [48]:
mat_inv=np.linalg.inv(mat)
mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [49]:
mat @ mat_inv

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

###고유값과 고유벡터


*   정방행렬(nxn) A에 대해서 Ax=λx를 만족하는 λ와 x를 각각 고유값과 고유 벡터라고 한다
*   np.linalg.eig() 로 계산



In [50]:
mat=np.array([[2,0,-2],[1,1,-2],[0,0,1]])
mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [51]:
np.linalg.eig(mat)

(array([1., 2., 1.]), array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

validation

In [52]:
eig_val, eig_vec=np.linalg.eig(mat)
eig_val

array([1., 2., 1.])

In [53]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [54]:
mat@eig_vec[:,0]  #Ax

array([0., 1., 0.])

In [55]:
eig_val[0]*eig_vec[:,0]#(lambda)x

array([0., 1., 0.])

## IV. Mission:

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [56]:
def get_L2_norm(mat):
  return np.linalg.norm(mat,2)

print(get_L2_norm(np.array([1,2,3,4])))

5.477225575051661


### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [60]:
def is_singular(mat):
  if np.linalg.det(mat)==0:
    return True
  else:
    return False

print(is_singular(np.array([[1,2],[3,4]])))

False
