# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

In [1]:
import numpy as np

## II. Numpy로 연산하기

In [4]:
x = np.array((1, 2, 3))
c = 5

print(f"더하기 : {x + c}")
print(f"빼기 : {x - c}")
print(f"곱하기 : {x * c}")
print(f"나누기 : {x / c}")

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vectorwise

In [5]:
y = np.array((1, 3, 5))
z = np.array((2, 9, 20))

print(f"더하기 : {y + z}")
print(f"빼기 : {y - z}")
print(f"곱하기 : {y * z}")
print(f"나누기 : {y / z}")

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


### Array Indexing and Slicing

In [16]:
W = np.array(([1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]))

# Indexing
print(W[0 ,0])
print(W[1, 2], end='\n\n')

# slicing
print(W[0:2, 1:3])
print(W[:2])
print(W[:2, :])
print(W[:, :3])

1
7

[[2 3]
 [6 7]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


### Array Broadcasting

##### Reproduce and operate

1. M x N, M x 1
2. M x N, 1 x N
3. M x 1, 1 x N

In [19]:
a = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
x = np.array((0, 1, 0))
y = np.array((0, 1, -1))

# 1. M x N, M x 1
print(a + x[:, None])

# 2. M x N, 1 x N
print(a * y)

# 3. M x 1, 1 x N
t = np.array((1, 2, 3))
u = np.array((2, 0, -2))
print(t[:, None] + u)

[[1 2 3]
 [5 6 7]
 [7 8 9]]
[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]
[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


## III. Numpy로 선형대수 지식 끼얹기

### Zero / One Vector / Matrix

- 'np.zeros(dim)'으로 생성, dim은 single value or tuple
- 'np.ones(dim)'으로 생성

In [25]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### Diagonal / Identity matrix

- np.diag(tuple), tuple은 elements of main diagonal
- np.eye(N, dtype=float64)

In [26]:
np.diag((1, 2))

array([[1, 0],
       [0, 2]])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Dot Product

- np.array.dot(np.array())

##### or

- np.array() @ np.array()

### Trace

##### main diagonal의 합

- np.array.trace()

### Determinant

- 행렬을 대표하는 값 중 하나
- 선현변환 과정에서 Vector의 Scaling 척도
- np.linalg.det(np.array())

### Inverse Matrix

### Eigenvalue and Eigenvector

- N x N 행렬 A에 대해 $Ax = \lambda x$를 만족하는 상수 $\lambda$와 이에 대응하는 벡터
- np.linalg.eig()

In [35]:
mat = np.array(((2, 0, -2), (1, 1, -2), (0, 0, 1)))

np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [40]:
def get_L2_norm(vector):
    return np.linalg.norm(vector)

### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [45]:
def is_singular(mat):
    return bool(np.linalg.det(mat))