# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

### numpy 가져오기

In [23]:
import numpy as np

In [25]:
#행렬
A = np.array([[3, 1, 2], [1, -2, 0], [1, 4, 2]])

print(f"A shape : {np.shape(A)}")
print(A)

A shape : (3, 3)
[[ 3  1  2]
 [ 1 -2  0]
 [ 1  4  2]]


In [26]:
#벡터
b = np.array([4, 1, 2])

print(f"b shape : {np.shape(b)}")
print(b)

b shape : (3,)
[4 1 2]


In [27]:
#역행렬
A_inv = np.linalg.inv(A)

print(f"A_inv shape : {np.shape(A_inv)}")
print(A_inv)

A_inv shape : (3, 3)
[[ 2.  -3.  -2. ]
 [ 1.  -2.  -1. ]
 [-3.   5.5  3.5]]


In [28]:
#Ax = b의 x 구하기 -> x = A_inv * b
x = A_inv @ b

print(f"x shape : {np.shape(x)}")
print(x)

x shape : (3,)
[ 1.00000000e+00 -6.66133815e-16  5.00000000e-01]


In [29]:
#결과 검증
bb = A @ x

print(f"bb shape : {np.shape(bb)}")
print(bb)

if np.linalg.norm(b - bb) < 1e-3: #일정 오차보다 작다면 OK
    print("OK")
else:
    print("Not OK")

bb shape : (3,)
[4. 1. 2.]
OK


## II. Numpy로 연산하기

### Scalar & Vector, Vector & Vector Operation

In [18]:
x = np.array([1, 2, 3])
c = 4

print("Vector x와 Scalar c의 연산")
print(f"{x + c}")
print(f"{x - c}")
print(f"{x * c}")
print(f"{x / c}")
print()

y = np.array([1, 3, 5])
z = np.array([2, 4, 6])

print("Vector y와 Vector z의 연산")
print(f"{y + z}")
print(f"{y - z}")
print(f"{y * z}")
print(f"{y / z}")

Vector x와 Scalar c의 연산
[5 6 7]
[-3 -2 -1]
[ 4  8 12]
[0.25 0.5  0.75]

Vector y와 Vector z의 연산
[ 3  7 11]
[-1 -1 -1]
[ 2 12 30]
[0.5        0.75       0.83333333]


## Array의 Broadcasting
- 기본적으로 같은 Type의 data에 대해서만 연산 가능하지만 만약에 피연산자가 연산 가능하도록 변환 가능하다면 연산을 가능하게 한다. 이를 **Broadcasting**이라 한다

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([0, 1, 0])

print(f"의도한 연산 방향이 아닌 예(x가 행벡터이기 때문) \n {a + x}")
print()

x = x[:, None]
print(f"의도한 연산 방향 (x를 전치) \n {a + x}")

의도한 연산 방향이 아닌 예(x가 행벡터이기 때문) 
 [[1 3 3]
 [4 6 6]
 [7 9 9]]

의도한 연산 방향 (x를 전치) 
 [[1 2 3]
 [5 6 7]
 [7 8 9]]


In [20]:
y = np.array([0, 1, -1])

print(f"a * y \n {a * y}")

a * y 
 [[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


In [21]:
t = np.array([1, 2, 3])
u = np.array([2, 0, -1])

#더하려고 하는데, t가 행벡터이기 때문에 열벡터로 바꿔줘야한다
t = t[:, None]

print(f"t + u \n {t + u}")

t + u 
 [[3 1 0]
 [4 2 1]
 [5 3 2]]


위의 계산은 이러한 형태와 같다

$$\begin{pmatrix} 1 & 1 & 1 \\ 2 & 2 & 2 \\ 3 & 3 & 3 \end{pmatrix} \quad + \quad \begin{pmatrix} 2 & 0 & -1 \\ 2 & 0 & -1 \\ 2 & 0 & -1 \end{pmatrix}$$

## III. Numpy로 선형대수 지식 끼얹기

### 영벡터(행렬)

In [30]:
print(np.zeros(1))
print()

print(np.zeros(2))
print()

print(np.zeros((3, 3)))

[0.]

[0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 일벡터(일행렬)

In [31]:
print(np.ones(1))
print()

print(np.ones(2))
print()

print(np.ones((3, 3)))

[1.]

[1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 대각행렬 (Diagonal Matrix)

In [32]:
print(np.diag((2, 4)))
print()

print(np.diag((1, 3, 5, 7)))

[[2 0]
 [0 4]]

[[1 0 0 0]
 [0 3 0 0]
 [0 0 5 0]
 [0 0 0 7]]


### 항등행렬 (Identity Matrix)

In [33]:
print(np.eye(2, dtype = int))
print()

print(np.eye(3, dtype = float))

[[1 0]
 [0 1]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 행렬곱 (Dot product)

In [34]:
A = np.array([[1, 4], [2, 3]])
B = np.array([[7, 9], [0, 6]])

print(f"A * B \n {A @ B}")

A * B 
 [[ 7 33]
 [14 36]]


### trace (Main Diagonal의 합)

In [36]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"arr \n{arr}")
print()

print(f"arr의 trace(Main Diagonal의 합) \n {arr.trace()}")
print()

print(f"크기 2인 항등행렬의 trace \n {np.eye(2, dtype = int).trace()}")

arr 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

arr의 trace(Main Diagonal의 합) 
 15

크기 2인 항등행렬의 trace 
 2


### Determinant

In [37]:
arr_2 = np.array([[2, 3], [1, 6]])

print(f"arr_2 \n{arr_2}")
print()

print(f"det(arr_2) \n{np.linalg.det(arr_2)}")
print()

arr_3 = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
print(f"arr_3 \n{arr_3}")
print()

print(f"det(arr_3) \n{np.linalg.det(arr_3)}")

arr_2 
[[2 3]
 [1 6]]

det(arr_2) 
9.000000000000002

arr_3 
[[1 4 7]
 [2 5 8]
 [3 6 9]]

det(arr_3) 
0.0


### 역행렬

In [38]:
mat = np.array([[1, 4], [2, 3]])
print(f"mat \n{mat}")
print()

mat_inv = np.linalg.inv(mat)

print(f"mat_inv \n{mat_inv}")
print()

print(f"mat @ mat_inv \n{mat @ mat_inv}")

mat 
[[1 4]
 [2 3]]

mat_inv 
[[-0.6  0.8]
 [ 0.4 -0.2]]

mat @ mat_inv 
[[1. 0.]
 [0. 1.]]


## 고유값과 고유벡터 (Eigenvalue & Eigenvector)
- 정방행렬(n*n) A에 대해 $Ax = \lambda x$ 를 만족하는 $\lambda$ 와 x를 각각 고유값과 고유벡터라고 한다

In [39]:
mat = np.array([[2, 0, -2], [1, 1, -2], [0, 0, 1]])
print(f"mat \n{mat}")
print()

eigval, eigvec = np.linalg.eig(mat)
print(f"mat's eigenvalue & eigenvector")
print(eigval)
print(eigvec)

mat 
[[ 2  0 -2]
 [ 1  1 -2]
 [ 0  0  1]]

mat's eigenvalue & eigenvector
[1. 2. 1.]
[[0.         0.70710678 0.89442719]
 [1.         0.70710678 0.        ]
 [0.         0.         0.4472136 ]]


### Eigenvalue, Eigenvector Validation

In [40]:
for i in range(len(mat)):
    print(mat @ eigvec[:, i]) # Ax

[0. 1. 0.]
[1.41421356 1.41421356 0.        ]
[0.89442719 0.         0.4472136 ]


In [41]:
for i in range(len(mat)):
    print(eigval[i] * eigvec[:, i]) # (lambda)x

[0. 1. 0.]
[1.41421356 1.41421356 0.        ]
[0.89442719 0.         0.4472136 ]


## IV. Exercises

## IV. Mission:

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [3]:
import numpy as np

v = [1, 2, 4, 5]

def get_L2_norm(v):
    return np.sqrt(np.sum([i**2 for i in v]))

print(get_L2_norm(v))

6.782329983125268


### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [16]:
a = [[1, 3], [2, 6]]
b = [[1, 4], [5, 2]]

def is_singular(v2):
    if np.linalg.slogdet(v2)[0] == 0: return True 
    else: return False
    
print(is_singular(a))
print(is_singular(b))

True
False
