# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

arr = [1,'two',3.0]

단점 리스트가 느리다...
c로 만든 라이브러리를 사용하자! -> numpy

### numpy 모듈 불러오기

In [2]:
import numpy as np

### why numpy?

**list**

In [6]:
L = range(1000)

%timeit [i**2 for i in L]

468 µs ± 25.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


**numpy**

In [9]:
N = np.arange(1000)

%timeit N ** 2

1.4 µs ± 251 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## numpy.array

numpy의 container array

In [10]:
arr = np.array([1, 2, 3])

arr

array([1, 2, 3])

In [12]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr.shape

(3,)

In [19]:
arr_2d.shape

NameError: name 'arr_2d' is not defined

## (numpy 실습)

### 행렬과 벡터 계산 

In [15]:
A = np.array([[3, 1, 1], [1, -2, -1], [1, 1, 1]])

print(A)
print(np.shape(A))

[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)


In [18]:
# 벡터 코딩
b = np.array([4, 1, 2])

print(b)
print(np.shape(b))

#, 가 나오는 이유는?? (3) 이렇게 표현되면 파이썬이 그냥 숫자로 판단하기 때문


[4 1 2]
(3,)


In [20]:
#역행렬 구하기
A_inv = np.linalg.inv(A)

print(A_inv)
print(np.shape(A_inv))


[[ 5.00000000e-01 -7.40148683e-17 -5.00000000e-01]
 [ 1.00000000e+00 -1.00000000e+00 -2.00000000e+00]
 [-1.50000000e+00  1.00000000e+00  3.50000000e+00]]
(3, 3)


In [22]:
# 역행렬을 이용해 변수들 구하기
# x = np.matmul(A_inv, b)
x = A_inv @ b

print(x)
print(np.shape(x))

[ 1. -1.  2.]
(3,)


In [24]:
# 결과 검증
# bb = np.mapmul(A, x)
bb = A @ x

print(bb)
print(np.shape(bb))

# 벡터끼리 빼준다음에 오차율이 굉장히 적으면 (벡터의 크기{norm}이 작으면) 서로 같다고 판단.
if np.linalg.norm(b-bb) < 1e-3:
    print('OK')
else :
    print('something wrong')

[4. 1. 2.]
(3,)
OK


In [ ]:
## (numpy 실습)

### 행렬과 벡터 계산 

A = np.array([[3, 1, 1], [1, -2, -1], [1, 1, 1]])

print(A)
print(np.shape(A))

# 벡터 코딩
b = np.array([4, 1, 2])

print(b)
print(np.shape(b))

#, 가 나오는 이유는?? (3) 이렇게 표현되면 파이썬이 그냥 숫자로 판단하기 때문


#역행렬 구하기
A_inv = np.linalg.inv(A)

print(A_inv)
print(np.shape(A_inv))


# 역행렬을 이용해 변수들 구하기
# x = np.matmul(A_inv, b)
x = A_inv @ b

print(x)
print(np.shape(x))

# 결과 검증
# bb = np.mapmul(A, x)
bb = A @ x

print(bb)
print(np.shape(bb))

# 벡터끼리 빼준다음에 오차율이 굉장히 적으면 (벡터의 크기{norm}이 작으면) 서로 같다고 판단.
if np.linalg.norm(b-bb) < 1e-3:
    print('OK')
else :
    print('something wrong')

## II. Numpy로 연산하기

### Vector와 scalar 사이의 연산 

벡터와 스칼라 사이의 연산은 그냥 연산자만 사용해줘도 된다. 

In [5]:
x = np.array([1, 2, 3])
c = 5

print("더하기 : {}".format(x + c))
print("빼기 : {}".format(x - c))
print("곱하기 : {}".format(x * c))
print("나누기 : {}".format(x / c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산 

벡터의 같은 인덱스끼리 연산이 진행된다. 

In [6]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])
# 기본적으로 array의 인자는 하나이기때문에 꼭 묶어줘야한다. 

print("더하기 : {}".format(y + z))
print("빼기 : {}".format(y - z))
print("곱하기 : {}".format(y * z))
print("나누기 : {}".format(y / z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


### Numpy의 indexing 

파이썬에서는 [][]로 인덱싱 
넘파이에서는 [ , ]로 인덱싱 하는 것에 주의 

In [7]:
w = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

print(w[0,1])

print(w[1,2])

print(w[2])

2
6
[7 8 9]


### array의 슬라이싱

In [14]:
w = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

# 23 행기준 0~1
# 56 열기준 1~2
w[0:2,1:3]

w[:,1:3]


array([[2, 3],
       [5, 6],
       [8, 9]])

### array의 broadcasting

1. M X N , M X 1  
    이 경우 열 벡터를 여러개로 복사해서 계산을 진행한다.   
    여기서 곱연산을 진행하면 각각의 원소에 대해 연산을 진행하는 것이지  
    행렬곱을 하는 것이 아니다. 
    
    그래서 두 행렬의 크기가 같아져야한다.    
    M X 1 과  1 X N이 주어지면  
    M X N 행렬이 만들어져 각 원소에 대해 계산한다. 

In [36]:
x = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
y = np.array([[0],[1],[0]])

z = np.array([0, 1, 0])
print(z[:].shape)
print(z[:][0])
print(z[None,:].shape)
print(z[None,:][0])



z = z[:, None] # 행은 모두 가져오고 열은 없다. -> 전치가 되어 y랑 같아진다. 
# https://stackoverflow.com/questions/37867354/in-numpy-what-does-selection-by-none-do

x - y

x - z

(3,)
0
(1, 3)
[0 1 0]


array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

## III. Numpy로 선형대수 지식 끼얹기

### 영벡터

In [41]:
# np.zeros(dim) dim은 값이나 튜플로 전달 (,)
np.zeros((4,3,2)) # 텐서, 행, 열 순서

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

### 일행렬 
원소가 모두 1인 행렬  
np.ones(dim) dim은 값이나 튜플(,)

In [42]:
np.ones(2)

array([1., 1.])

In [43]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 대각행렬(diagonal matrix)

대각선을 제외한 행렬이 0인 행렬  
튜플의 형태로 입력값을 넣어주면  
n X n 행렬이 나온다.

In [46]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [47]:
np.diag((1,2,3,4))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### 항등행렬(identity matrix)
main diagonal 이 1인 행렬을 뜻합니다. 크기는 n X n 입니다.  
np.eye(n, dtype= 원소의 데이터타입)  
데이터 타입에는 int, float uint, complex 등 여러가지가 있습니다. 

In [48]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [49]:
np.eye(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 행렬 곱 (dot product)

.dot() 혹은 @ 연산자를 사용할 수 있습니다. 


In [52]:
mat1 = np.array([[1, 4],[2, 3]])
mat2 = np.array([[7, 9],[0, 6]])

print(mat1.dot(mat2))
print(mat2.dot(mat1))

[[ 7 33]
 [14 36]]
[[25 55]
 [12 18]]


In [53]:
mat1 @ mat2

array([[ 7, 33],
       [14, 36]])

### trace (main diagonal 의 합)
np.trace()를 사용

In [54]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr.trace()

15

In [57]:
np.eye(3).trace()

3.0

### 행렬식 (determinant)
np.linalg.det(구하고자하는 행렬)  
선형식으로 벡터를 변화시키는 척도 (scaling)

In [59]:
arr = np.array([[2, 3],[1, 6]])
arr

array([[2, 3],
       [1, 6]])

In [61]:
np.linalg.det(arr)

9.000000000000002

In [62]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
np.linalg.det(arr)

0.0

### 역행렬
np.linalg.inv(행렬)  
만약 arr의 행렬식이 0이면 오류가 출력됩니다. 

In [70]:
arr = np.array([[3,2,3],[4,5,6],[7,8,9]])
arr

array([[3, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr_inv = np.linalg.inv(arr)
arr_inv

array([[ 0.5       , -1.        ,  0.5       ],
       [-1.        , -1.        ,  1.        ],
       [ 0.5       ,  1.66666667, -1.16666667]])

In [72]:
arr @ arr_inv

array([[ 1.00000000e+00,  0.00000000e+00,  4.44089210e-16],
       [-2.22044605e-16,  1.00000000e+00,  8.88178420e-16],
       [-1.11022302e-16,  8.88178420e-16,  1.00000000e+00]])

In [73]:
arr = np.array([[2, 3],[1, 6]])
arr

array([[2, 3],
       [1, 6]])

In [74]:
arr_inv = np.linalg.inv(arr)
arr_inv

array([[ 0.66666667, -0.33333333],
       [-0.11111111,  0.22222222]])

In [75]:
arr @ arr_inv

array([[1., 0.],
       [0., 1.]])

### 고윳값 (eigenvalue & eigen vecter)
$Ax = (\lambda)x$ 를 만족 시키는 람다와 우항의 x를 의미한다. 
방향은 지키면서 span 되는 크기는 고유값 영역을 고유벡터라 한다.  
np.linalg.eig() 로 계산한다. 

In [76]:
arr = np.array([[3,2,3],[4,5,6],[7,8,9]])
arr

array([[3, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
np.linalg.eig(arr)

(array([16.36660027,  1.        , -0.36660027]),
 array([[-0.2603943 , -0.82956136, -0.30110589],
        [-0.5207886 ,  0.51847585, -0.60221177],
        [-0.8130031 ,  0.20739034,  0.73937557]]))

normalization이 일어난 상태이며, 위 array에 대해 세로로 확인해야 한다. 

### 고유값 검증

In [81]:
eig_val, eig_vec = np.linalg.eig(arr)

In [82]:
eig_vec[:,0]

array([-0.2603943, -0.5207886, -0.8130031])

In [79]:
arr @ eig_vec[:,0]

array([ -4.2617694,  -8.5235388, -13.3060968])

In [80]:
eig_val[0] * eig_vec[:,0]

array([ -4.2617694,  -8.5235388, -13.3060968])

## IV. Mission:

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [1]:
import numpy as np

In [6]:
def get_L2_norm(vec):
    return np.sqrt(np.sum(vec ** 2))

In [13]:
arr = np.array([2,2,4,1])

In [14]:
print(get_L2_norm(arr))

5.0


### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [16]:
def is_singular(arr):
    if (np.linalg.det(arr) == 0):
        return True
    return False

In [17]:
arr = np.array([[2, 3],[1, 6]])
is_singular(arr)

False

In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
is_singular(arr)

True