# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

### Remind : 리스트

In [ ]:
arr = [1, "two", 3.0]

print(arr)

[1, 'two', 3.0]


### numpy 모듈 불러오기

In [ ]:
import numpy as np

### 왜 numpy를 사용해야 할까요?

**List**  
% timeit : 작은 코드 세그먼트의 실행 속도를 측정해주는 기능. 모듈 앞에 %를 붙임으로써 사용하는 노트북 환경에서의 특수한 키워드

In [ ]:
L = range(1000)

%timeit [i**2 for i in L]

226 µs ± 25.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


**numpy.array**

In [ ]:
# 해당 범위의 데어터를 모두 array에 담아주는 numpy의 arange 사용
N = np.arange(1000)

%timeit N**2

1.27 µs ± 25.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Numpy.array

파이썬에 리스트가 있다면 numpy에는 array가 있다.  
numpy의 Container, array  
np.array(일반적으로 리스트)의 형태로 사용

In [ ]:
arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# array의 차원을 알려주는 기능
arr.shape

(3,)

In [ ]:
arr_2d.shape

(3, 3)

## II. Numpy로 연산하기

## Vector와 Scalar 사이의 연산  
벡터의 각 원소에 대해서 연산을 진행

In [ ]:
x = np.array([1, 2, 3])
c = 5

print("더하기 : {}".format(x+c))
print("빼기 : {}".format(x-c))
print("곱하기 : {}".format(x*c))
print("나누기 : {}".format(x/c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산  
벡터의 **같은 인덱스**끼리 연산이 진행된다.

In [ ]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print("더하기 : {}".format(y+z))
print("빼기 : {}".format(y-z))
print("곱하기 : {}".format(y*z))
print("나누기 : {}".format(y/z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


### Array의 Indexing  
Python의 List와 유사하게 진행  
단, 파이썬에서는 w[0][1] 이런 식으로 썼다면 넘파이에서는 w[0,1] 이런 형식  
[(row), (column)]  
3차원 이상이라면 [a, b, c, ...]

In [ ]:
w = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

w[0, 0]

1

In [ ]:
w[2, 3]

12

In [ ]:
w[1, 2]

7

### Array의 Slicing  
Python의 List와 유사하게 진행

In [ ]:
w = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 2, 3, 6, 7 이라는 원소만 가져오고 싶을 때
# numpy에서는 [행 범위, 열 범위] 로 표현
w[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [ ]:
# 1,2,3,4, 5,6,7,8 가져오고 싶을 때
w[0:2, 0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
w[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
w[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# 3,4, 7,8, 11,12 가져오고 싶을 때
w[0:3,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [ ]:
w[:,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

### Array의 Broadcasting  
  
  기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능하지만 만약에 피연산자가 연산 가능하도록 변환이 가능하다면 연산이 가능하다. 이를 **Broadcasting**이라고 한다.  

Numpy의 Array가 연산을 진행하는 특수한 방법! 연산의 용이성을 위해 개발되었다.  
1. M X N, M X 1 : M X 1 행렬을 열을 복제해서 M X N으로 맞춰주고 계산을 진행.
2. M X N, 1 X N : 1 X N 행렬의 행을 복제해서 M X N으로 맞춰주고 계산을 진행.
3. M X 1, 1 X N : 각각 열과 행을 복제해서 둘다 M X N으로 맞춰주고 계산을 진행.  
  
여기서 연산은 사칙연산 모두 해당하며 곱하기 연산은 행렬의 곱 과는 다른 그냥 각 인덱스의 엘리먼트끼리 곱하는 연산을 말한다.


#### 1. M by N, M by 1

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0,1,0])

# 여기서 x는 행벡터이므로 전치를 시켜줘야함
x = x[:, None] # 행은 전부 가져오고 열은 None

print(x)
print(a+x)

[[0]
 [1]
 [0]]
[[1 2 3]
 [5 6 7]
 [7 8 9]]


####2. M by N, 1 by N

In [ ]:
y = np.array([0, 1, -1])

print(a * y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


####3. M by 1, 1 by N

In [ ]:
t = np.array([1, 2, 3]) # 이거 열 벡터로 바꿔줘야 함
t = t[:, None] # Transpose
u = np.array([2, 0, -2])

print(t + u)

# 1 1 1   2 0 -2
# 2 2 2 + 2 0 -2
# 3 3 3   2 0 -2

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


## III. Numpy로 선형대수 지식 끼얹기

#### A. basics

#### 영벡터(행렬)  
- 원소가 모두 0인 벡터(행렬)  
- np.zeros(dim) 을 통해 생성, dim은 값, 혹은 튜플( , )

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

#### 일벡터(행렬)  
- 원소가 모두 1인 벡터(행렬)
- np.ones(dim)을 통해 생성, dim은 값, 혹은 튜플( , )

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 대각행렬 (Diagonal Matrix)  
- Main Diagonal을 제외한 성분이 0인 행렬
- np.diag((main_diagonal))을 통해 생성

In [ ]:
np.diag((2, 4))

array([[2, 0],
       [0, 4]])

In [ ]:
np.diag((1, 3, 5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

#### 항등행렬 (Identity Matrix)  
- Main Diagonal이 1인 대각행렬
- np.eye(n, (dtype=int, uint, float, complex, ...))를 사용

In [ ]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 행렬곱 (Dot Product)  
- 행렬간에 정의되는 곱연산
- np.dot() or @ 사용

In [ ]:
mat_1 = np.array([[1, 4], [2, 3]])
mat_2 = np.array([[7, 9], [0, 6]])

mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

In [ ]:
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

#### 트레이스 (Trace)  
- Main Diagonal의 합
- np.trace()를 사용

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.trace()

15

In [ ]:
np.eye(2, dtype=int).trace()

2

#### 행렬식 (Determinant)  
- 행렬을 대표하는 값들 중 하나
- 선형변환 과정에서 Vector의 Scaling 척도
- np.linalg.det()으로 계산

In [ ]:
arr_2 = np.array([[2, 3], [1, 6]])

arr_2

array([[2, 3],
       [1, 6]])

In [ ]:
np.linalg.det(arr_2)

9.000000000000002

In [ ]:
arr_3 = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])

arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.linalg.det(arr_3)

0.0

#### 역행렬 (Inverse Matrix)  
- 행렬 A에 대해 AB = BA = I를 만족하는 행렬 B = A^-1
- `np.linalg.inv()`으로 계산

In [ ]:
mat = np.array([[1, 4], [2, 3]])

mat

array([[1, 4],
       [2, 3]])

In [ ]:
mat_inv = np.linalg.inv(mat)

mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [ ]:
mat @ mat_inv

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

In [ ]:
mat_3by3 = np.arange(1, 19, 2)
mat_3by3 = mat_3by3.reshape((3, 3))
mat_3by3

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [ ]:
mat_3by3_inv = np.linalg.inv(mat_3by3)

mat_3by3_inv

array([[-2.81474977e+14,  5.62949953e+14, -2.81474977e+14],
       [ 5.62949953e+14, -1.12589991e+15,  5.62949953e+14],
       [-2.81474977e+14,  5.62949953e+14, -2.81474977e+14]])

#### 고유값과 고유벡터 (Eigenvalue and Eigenvector)  
- 정방행렬(nxn) A에 대해 $Ax = \lambda x$를 만족하는 상수 $\lambda$와 이에 대응하는 벡터  
- `np.linalg.eig()`으로 계산

In [ ]:
mat = np.array([[2, 0, -2], [1, 1, -2], [0, 0, 1]])

mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [ ]:
np.linalg.eig(mat) # 고유값과 고유벡터를 각각 리턴하는데 고유벡터는 열 기준으로 봐야한다.

(array([1., 2., 1.]), array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

Validation

In [ ]:
eig_val, eig_vec = np.linalg.eig(mat)

eig_val

array([1., 2., 1.])

In [ ]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [ ]:
mat @ eig_vec[:, 0]

array([0., 1., 0.])

In [ ]:
eig_val[0] * eig_vec[:, 0] # (lambda) x

array([0., 1., 0.])

In [ ]:
mat @ eig_vec[:, 1]

array([1.41421356, 1.41421356, 0.        ])

In [ ]:
eig_val[1] * eig_vec[:, 1] # (lambda) x

array([1.41421356, 1.41421356, 0.        ])

In [ ]:
mat @ eig_vec[:, 2]

array([0.89442719, 0.        , 0.4472136 ])

In [ ]:
eig_val[2] * eig_vec[:, 2] # (lambda) x

array([0.89442719, 0.        , 0.4472136 ])

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [3]:
import numpy as np

def get_L2_norm(vect):
    return np.linalg.norm(vect)

def get_L2_norm2(vect):
    norm = 0
    for i in vect:
        norm += i * i
    return np.sqrt(norm)

test = np.array([3,4])
print(get_L2_norm(test))
print(get_L2_norm2(test))


5.0
5.0


### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [6]:
import numpy as np

def is_singular(vect):
    try:
        np.linalg.inv(vect)
        return False
    except:
        return True
    
def is_singular2(vect):
    if np.linalg.det(vect) == 0:
        return True
    else:
        return False

test = [[2,3],[6,9]]
test2 = [[1,2],[3,4]]

print(is_singular(np.array(test)))
print(is_singular(np.array(test2)))
print(is_singular2(np.array(test)))
print(is_singular2(np.array(test2)))

True
False
True
False
