# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

#### Remind:리스트

In [1]:
arr = [1, "two", 3.0]
print(arr)

[1, 'two', 3.0]


#### numpy 모듈 불러오기

In [5]:
import numpy as np

#### 왜 numpy를 사용해야 할까?

#### List


In [3]:
L = range(1000)

%timeit [i**2 for i in L]

184 µs ± 390 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### numpy.array

In [7]:
N = np.arange(1000)

%timeit N ** 2

1.37 µs ± 5.96 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [9]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr.shape

(3,)

In [11]:
arr_2d.shape

(3, 3)

## II. Numpy로 연산하기

#### Vector와 Scalar의 연산  
벡터의 각 원소에 대해서 연산을 진행

In [15]:
x = np.array([1, 2, 3])
c = 5

print("더하기 : {}".format(x+c))
print("빼기 : {}".format(x-c))
print("곱하기 : {}".format(x*c))
print("나누기 : {}".format(x/c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


#### Vector와 Vector의 연산  
벡터의 **같은 인덱스**끼리 연산

In [17]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print("더하기 : {}".format(y+z))
print("빼기 : {}".format(y-z))
print("곱하기 : {}".format(y*z))
print("나누기 : {}".format(y/z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


#### Array Indexing
Python의 리스트와 유사

In [19]:
W = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

W[0,0]

1

In [21]:
W[2,3]

12

#### Array Slicing  
python의 리스트와 유사

In [22]:
W[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [23]:
W[0:2, 0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
W[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
W[:, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

#### Array Broadcasting
Numpy가 연산을 진행하는 특수한 방법  
기본적으로 같은 Type의 data에 대해서만 연산이 적용  
하지만 피연산자가 연산 가능하도록 변환이 가능하다면 연산이 가능  
이를 **Brodcasting**이라고 함.

#### 1.M by N, M by 1

In [30]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([0, 1, 0])

# 전치
x = x[:, None]

# 1 2 3   0 0 0
# 4 5 6 + 1 1 1
# 7 8 9   0 0 0
print(a+x)

[[1 2 3]
 [5 6 7]
 [7 8 9]]


#### 2. M by N, 1 by N

In [31]:
y = np.array([0, 1, -1])

#  1 2 3   0 1 -1
#  4 5 6 * 0 1 -1
#  7 8 9   0 1 -1
print(a * y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


#### 3. M by 1, 1 by N

In [32]:
t = np.array([1, 2, 3])
t = t[:,None]

u = np.array([2, 0, -2])

# 1 1 1   2 0 -2
# 2 2 2 + 2 0 -2
# 3 3 3   2 0 -2
print(t + u)


[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


## III. Numpy로 선형대수 지식 끼얹기

#### 영벡터(행렬)
- 원소가 모두 0인 벡터(행렬)
- np.zeros(dim)을 통해 생성. dim은 값, 혹은 튜플

In [33]:
np.zeros(3)

array([0., 0., 0.])

In [34]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

#### 일행렬
- 원소가 모두 1인 벡터(행렬)
- np.ones(dim)을 통해 생성. dim은 값, 튜플

In [35]:
np.ones(2)

array([1., 1.])

In [36]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 대각행렬

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [6]:
# def get_L2_norm():
import numpy as np
def get_L2_norm(x):
    return np.linalg.norm(x, ord=2)

### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [ ]:
def is_singular(x):
    if np.linalg.det(x) != 0:abs
        return True
    else:
        return False