# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

In [4]:
import numpy as np

## II. Numpy로 연산하기

## III. Numpy로 선형대수 지식 끼얹기

A. basics

### 영백터(행렬)

- 원소가 모두 0인 벡터(행렬)
- np.zeros(dim)을 통해 생성

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### 일행렬

 - 원소가 모두 1인 벡터(행렬)
 - 'np.ones(dim)'을 통해 생성

In [8]:
np.ones(2)

array([1., 1.])

In [9]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### 대각행렬

 -  Main Diagonal을 제외한 성분이 0인 행렬
 - 'np.diag(main(diagonals))를 통해 생성

In [10]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [11]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### 항등행렬
 - Main diagonal이 1인 대각행렬
 - 'np.eye(n, (dtype))'를 통해 생성 default = float

In [12]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [13]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### 행렬곱

 - 행렬간에 정의되는 곱 연산
 - `np.dot()`, `@`를 사용

In [16]:
mat_1 = np.array([[1,4],[2,3]])
mat_2 = np.array([[7,9],[0,6]])

mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

In [17]:
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

B. furthermore

### 트레이스(trace)
 
 - Main diagonal의 합
 - `np.trace()`를 사용

In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr.trace()

15

In [22]:
np.eye(2, dtype = int).trace()

2

### 행렬식

 - 행렬을 대표하는 값들 중 하나
 - 선형변환 과정에서 Vector의 Scaling 척도
 - `np.linalg.det()`

In [27]:
arr_2 = np.array([[2,3],[1,6]])

arr_2

array([[2, 3],
       [1, 6]])

In [28]:
np.linalg.det(arr_2)

9.000000000000002

In [31]:
arr_3 = np.array([[1,4,7],[2,5,8],[3,6,9]])

arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [32]:
np.linalg.det(arr_3)

0.0

### 역행렬
 
 - 행렬 A에 대해 AB = BA = I를 만족하는 행렬 B = A^-1
 - `np.linalg.inv()`

In [44]:
mat = np.array([[1,4],[2,3]])

mat

array([[1, 4],
       [2, 3]])

In [45]:
mat_inv = np.linalg.inv(mat)

mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [46]:
mat @ mat_inv

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

In [53]:
mat = np.array([[1,4,3],[4,6,6],[7,1,9]])

mat

array([[1, 4, 3],
       [4, 6, 6],
       [7, 1, 9]])

In [54]:
mat_inv2 = np.linalg.inv(mat)

mat_inv2

array([[-1.14285714,  0.78571429, -0.14285714],
       [-0.14285714,  0.28571429, -0.14285714],
       [ 0.9047619 , -0.64285714,  0.23809524]])

In [55]:
mat @ mat_inv2

array([[ 1.00000000e+00,  1.11022302e-16,  2.77555756e-17],
       [-4.44089210e-16,  1.00000000e+00,  5.55111512e-17],
       [-2.22044605e-16,  3.33066907e-16,  1.00000000e+00]])

### 고유값과 고유벡터

 - 정방행렬 A에 대해  $Ax = \lambda x$를 만족하는 $\lambda x$와 x를 각각 고유값과 고유 벡터라 한다.
 - `np.linalg.eig()`으로 계산

In [56]:
mat = np.array([[2,0,-2],[1,1,-2],[0,0,1]])

np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

010이 eigvector

### Validation

In [57]:
eig_val, eig_vec = np.linalg.eig(mat)

eig_val

array([1., 2., 1.])

In [58]:
mat @ eig_vec[:,0] #Ax

array([0., 1., 0.])

In [59]:
eig_val[0] * eig_vec[:,0] #(lambda)x 충분한 차원이 없음 bordcast

array([0., 1., 0.])

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [61]:
def is_singular(nparray):
    if np.linalg.det(nparray) == 0:
        return True
    
    else:
        return False

In [62]:
is_singular([[1,2,3],[4,5,6],[7,8,9]])

True

In [63]:
is_singular([[1,2,3],[4,6,6],[7,8,9]])

False