# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

## II. Numpy로 연산하기

### Vector와 Scalar 사이의 연산

-> 벡터의 각 원소에 대해서 연산을 진행

$$ x = \left( \begin{matrix} 1 \\ 2 \\ 3 \end{matrix} \right) \quad c = 5 $$


In [2]:
import numpy as np

x = np.array([1, 2, 3])
c = 5

print(f"더하기: {x + c}")
print(f"빼기: {x - c}")
print(f"곱하기: {x * c}")
print(f"나누기: {x / c}")

더하기: [6 7 8]
빼기: [-4 -3 -2]
곱하기: [ 5 10 15]
나누기: [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산

-> 벡터의 **같은 인덱스**끼리 연산이 진행됨

$$ y = \left( \begin{matrix} 1 \\ 3 \\ 5 \end{matrix} \right) \quad z = \left( \begin{matrix} 2 \\ 9 \\ 20 \end{matrix} \right) $$

In [3]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print(f"더하기: {y + z}")
print(f"빼기: {y - z}")
print(f"곱하기: {y * z}")
print(f"나누기: {y / z}")

더하기: [ 3 12 25]
빼기: [ -1  -6 -15]
곱하기: [  2  27 100]
나누기: [0.5        0.33333333 0.25      ]


### Array Indexing

-> 대부분 python list와 동일하게 진행됨  
-> But [2][2] 대신 [2,2]로 씀

$$ w = \left( \begin{matrix} 1 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8 \\ 9 & 10 & 11 & 12 \end{matrix} \right) $$

In [6]:
w = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(w[0,0])
print(w[1,1])
print(w[2,3])

1
6
12


### Array Slicing
-> 대부분 python list와 동일하게 진행됨  
-> But, [1:2, 2:3] 형태로 씀 : [행의 시작:행의 끝-1, 열의 시작:열의 끝-1]

In [7]:
w[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [13]:
#행은 일부, 열은 전체 출력
print(w[0:2, 0:4])
print(w[0:2])
print(w[0:2,])
print(w[0:2,:])

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [15]:
#전체 배열 출력
print(w[0:3, 0:4])
print(w[:,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
#행은 전체, 열은 일부 출력 -> :,로만 가능 (, or 그냥 생략 불가)
print(w[0:3, 1:3])
print(w[:, 1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 2  3]
 [ 6  7]
 [10 11]]


### Array의 Broadcasting

-> 기본적으로는 같은 형태의 배열에 대해서만 연산이 가능함.  
-> But, 서로 다른 형태의 배열도 피연산자가 연산 가능하도록 변화가 가능하다면 연산 가능  
: 서로에게 맞춰서 변화해서 결과적으로 M x N 행렬끼리의 연산이 되어버림.

- M x N 과 M x 1 = 뒤의 열벡터가 N개 반복됨 (앞의 MxN 배열형태로 바뀌려고 함)
- M x N 과 1 x N = 뒤의 행벡터가 M개 반복됨 (앞의 MxN 배열형태로 바뀌려고 함)
- M x 1 과 1 x N = 앞의 열벡터는 N개 반복되고, 뒤의 행벡터는 M개 반복되서 결과적으로 M x N 과 M x N 행렬의 연산이 되어버림.

#### 1. M x N , M x 1

In [21]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0,1,0])   #기본적으로 행벡터
x = x[:, None] #행벡터를 열벡터로 바꿈

print(a + x) # 열벡터가 3개가 됨 -> x = [[0,1,0],[0,1,0],[0,1,0]]

[[1 2 3]
 [5 6 7]
 [7 8 9]]


#### M x N , 1 x N

In [23]:
y = np.array([0,1,-1])

print(a * y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


#### M x 1 , 1 x N

In [24]:
print(x + y)

[[ 0  1 -1]
 [ 1  2  0]
 [ 0  1 -1]]


# III. Numpy로 선형대수 지식 끼얹기

### 영벡터 (영행렬)

- 원소가 모두 0인 벡터(행렬)  
- np.zeros(dimension)을 통해 생성: dimension은 값 or tuple (,) 형식으로 가능  
- default: float, 다른 data type 지정가능: dtype = float, int, uint, complex .... (2번째 인자)

In [25]:
np.zeros(2)

array([0., 0.])

In [26]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
np.zeros((4,6,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### 일벡터 (일행렬)

- 원소가 모두 1인 벡터(행렬)
- np.ones(dim)을 통해 생성: 영행렬과 비슷한 인자를 갖음
- default: float (뒤에 소숫점 있음)

In [30]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.ones(3)

array([1., 1., 1.])

### 대각행렬 (diagnol matrix)

- Main Diagnol을 제외한 성분이 모두 0인 행렬
- np.diag(main_diagnol)을 통해 생성: 인자 한개로 묶어야함.
- 인자의 개수 = N인 경우 : 결과도 N x N 행렬

In [33]:
np.diag((4,9,3,2))

array([[4, 0, 0, 0],
       [0, 9, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 2]])

In [35]:
np.diag((2,3))

array([[2, 0],
       [0, 3]])

### 항등행렬 (identity matrix)

- Main Diagnol == 1인 대각행렬: 나머지 원소는 0
- np.eye(n)를 사용: N x N 행렬 생성됨.

In [36]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [37]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [39]:
np.eye(4).dtype #np.eye의 data type 확인가능

dtype('float64')

### 행렬곱 (dot product)

- 행렬간의 곱연산: 앞 행렬의 열 개수 = 뒤 행렬의 행 개수가 같아야지만 연산가능 
- np.dot() or @ 사용

In [49]:
a = np.array([[1,3,5],[2,4,6]])
b = np.array([[2,3,4],[5,6,7],[8,9,10]])

In [51]:
a @ b # 2x3 @ 3x3 = 2x3

array([[57, 66, 75],
       [72, 84, 96]])

In [52]:
a.dot(b)

array([[57, 66, 75],
       [72, 84, 96]])

### 트레이스 (trace)

- Main Diagnol의 합을 출력
- np.trace()를 사용

In [54]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [55]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr.trace()

15

In [57]:
np.eye(2, dtype=int).trace()  #항등행렬 2*2

2

In [58]:
np.diag((2,3,4)).trace()   #대각행렬 3*3: main diagnol 2,3,4

9

### 행렬식 (determiant)

- 행렬을 대표하는 값들 중 하나
- 선형변환 과정에서 Vector의 Scaling 척도
- np.linalg.det()로 계산

In [59]:
arr2 = np.array([[2,3],[1,6]])

In [60]:
arr2

array([[2, 3],
       [1, 6]])

In [61]:
np.linalg.det(arr2)

9.000000000000002

In [62]:
arr3 = np.array([[1,4,7],[2,5,8],[3,6,9]])

In [63]:
arr3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [64]:
np.linalg.det(arr3)

0.0

### 역행렬 (inverse matrix)

- 행렬 A에 대해 AB = BA = 1을 만족하는 행렬 B = A^-1
- np.linalg.inv()로 계산

In [65]:
arr4 = np.array([[1,4],[2,3]])

In [66]:
arr4

array([[1, 4],
       [2, 3]])

In [67]:
np.linalg.inv(arr4)

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [68]:
arr_4 = np.linalg.inv(arr4)
arr_4

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [71]:
arr4 @ arr_4 #오차범위내에 들어옴

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

### 고유값과 고유벡터 (eigenvalue & eigenvector)

- 정방행렬 A에 대해 Ax = (\lambda)x를 만족하는 상수 (\lambda)와 이에 대응하는 벡터 
- np.linalg.eig()로 계산

In [72]:
mat = np.array([[2,0,-2],[1,1,-2],[0,0,1]])

In [73]:
mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [74]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

In [78]:
eig_val, eig_vec = np.linalg.eig(mat)   #출력값이 두개이므로

eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [79]:
eig_val

array([1., 2., 1.])

In [80]:
mat @ eig_vec[:,0] #Ax

array([0., 1., 0.])

In [81]:
eig_val[0] * eig_vec[:, 0]  #lambda x

array([0., 1., 0.])

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [85]:
def get_L2_norm(arr):
    return np.linalg.norm(arr)

In [83]:
arr = np.array([1,2,3])

In [86]:
get_L2_norm(arr)

7.416198487095663

### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [99]:
def is_singular(arr):
    return not np.linalg.det(arr)

In [107]:
arr_a = np.array([[2,1],[4,2]])

In [108]:
is_singular(arr_a)

True

In [101]:
arr = np.array([[1,2],[3,4]])

In [102]:
is_singular(arr)

False