# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

## II. Numpy로 연산하기

## Vector와 Scalar 사이의 연산

벡터의 각 원소에 대해서 연산을 진행

In [2]:
import numpy as np

In [5]:
x = np.array([1,2,3])
c = 5
x = x / c

print(f"더하기 : {x}")

더하기 : [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산

벡터의 **같은 인덱스** 끼리 연산이 진행

In [23]:
y = np.array([[1,3,5,6], [7,9,10,11], [12,13,14,15]])
z = np.array([2,9,20,10])

print(f"더하기 : {y + z}")
print(f"Indexing : {y[0, 1]}")

더하기 : [[ 3 12 25 16]
 [ 9 18 30 21]
 [14 22 34 25]]
Indexing : 3


## Array Slicing

Python의 리스트와 유사하게 진행

In [24]:
y[0:2, 1:3]

array([[ 3,  5],
       [ 9, 10]])

In [25]:
y[0:2]

array([[ 1,  3,  5,  6],
       [ 7,  9, 10, 11]])

In [26]:
y[0:3, 2:4]

array([[ 5,  6],
       [10, 11],
       [14, 15]])

In [30]:
y[:, 2:]

array([[ 5,  6],
       [10, 11],
       [14, 15]])

## Array 의 Broadcasting

자동으로 커지는 np.array. 행과 열을 맞춰줍니다.

기본적으로 같은 Type의 data에서만 연산이 적용 가능
하지만 만약에 피연산자가 연산 가능하도록 변환이 가능하다면 연산이 가능합니다.  
이를 **Broadcasting**이라고 합니다.

In [34]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0,1,0])

x = x[:, None] #x를 전치
print(x)
print(a+x)

[[0]
 [1]
 [0]]
[[1 2 3]
 [5 6 7]
 [7 8 9]]


In [35]:
y = np.array([0,1,-1])
print(a*y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


In [36]:
t = np.array([1,2,3])
t = t[:, None] #transpose
u = np.array([2,0,-2])

print(t + u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


## III. Numpy로 선형대수 지식 끼얹기

## A. basics

### 영벡터(행렬)

- 원소가 모두 0임

In [39]:
x = np.zeros(2)

In [40]:
np.zeros([3, 3, 3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### 일행렬

In [41]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 대각행렬(diagonal matrix)

In [42]:
np.diag([2, 4])

array([[2, 0],
       [0, 4]])

In [43]:
np.diag([1,3,5,7,9])

array([[1, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 9]])

### 항등행렬

In [48]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [47]:
np.eye(3, dtype=complex) #complex는 복소수

array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j]])

### 행렬 곱 (dot product)

In [51]:
mat_1 = np.array([[1,4], [2,3]])
mat_2 = np.array([[7, 9], [0, 6]])

print(mat_1 @ mat_2)
print(mat_1.dot(mat_2))

[[ 7 33]
 [14 36]]
[[ 7 33]
 [14 36]]


### trace

- main diagonal의 sum
- `np.trace()`를 사용

In [54]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.trace()

15

In [56]:
np.eye(2, dtype=int).trace()

2

### 행렬식

- 행렬을 대표하는 값들 중 하나
- 선형변환 과정에서 Vector의 Scaling 척도
- `np.linalg.det()`으로 계산

In [58]:
arr_2 = np.array([[2,3],[1,6]])
np.linalg.det(arr_2)

9.000000000000002

In [59]:
arr_3 = np.array([[1,4,7],[2,5,8],[3,6,9]])
np.linalg.det(arr_3)

0.0

### 역행렬

In [64]:
mat = np.array([[1,4],[2,3]])
mat_inv = np.linalg.inv(mat)
print(mat_inv)

[[-0.6  0.8]
 [ 0.4 -0.2]]


In [65]:
mat@mat_inv

array([[1., 0.],
       [0., 1.]])

### eigenvalue, eigenvector

- 정방행렬(nxn) A에 대해서 $Ax = \lambda x$을 만족하는 $\lambda$와 x를 각각 고유값과 고유벡터라고 한다.

In [66]:
mat = np.array([[2,0,-2], [1,1,-2],[0,0,1]])

In [67]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

#### Validation

In [71]:
eig_val, eig_vec = np.linalg.eig(mat)

In [73]:
eig_vec[:, 0]

array([0., 1., 0.])

In [70]:
mat @ eig_vec[:, 0]

array([0., 1., 0.])

In [72]:
eig_val[0] * eig_vec[:, 0]# lambda x

array([0., 1., 0.])

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [78]:
def get_L2_norm(mat):
    return np.linalg.norm(mat)

mat = np.array([1,2,3])
number = get_L2_norm(mat)

print(number)

3.7416573867739413


### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [80]:
def is_singular(mat):
    if np.linalg.det(mat) == 0:
        return True
    else:
        return False

mat = np.array([[1,4,7],[2,5,8],[3,6,9]])
print(is_singular(mat))

mat = np.array([[2,3],[1,6]])
print(is_singular(mat))

True
False
