# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

## II. Numpy로 연산하기

In [4]:
import numpy as np

x = np.array([1,2,3])
c = 5
print(f'addition : {x+c}')
print(f'subtraction : {x-c}')
print(f'multiply : {x*c}')
print(f'division : {x/c}')

addition : [6 7 8]
subtraction : [-4 -3 -2]
multiply : [ 5 10 15]
division : [0.2 0.4 0.6]


In [19]:
y = np.array([1,2,3])
d = np.array([2,10,20])
print(f'addition : {y+d}')
print(f'subtraction : {y-d}')
print(f'multiply : {y*d}')
print(f'division : {y/d}')

addition : [ 3 12 23]
subtraction : [ -1  -8 -17]
multiply : [ 2 20 60]
division : [0.5  0.2  0.15]


In [21]:
W = np.arange(12).reshape(3,4)
print(W)
print(f'row0: {W[0]}')
print(f'col1: {W[:,1]}')
print(f'slice:\n {W[:2, 2:]}')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
row0: [0 1 2 3]
col1: [1 5 9]
slice:
 [[2 3]
 [6 7]]


## III. Numpy로 선형대수 지식 끼얹기

In [35]:
print(f'zero : \n{np.zeros((3,3))}')
print(f'one : \n{np.ones((3,3))}')
print(f'diagonal : \n{np.diag(range(1,6))}')
print(f'identity : \n{np.eye(4, dtype=int)}')


zero : 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
one : 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
diagonal : 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
identity : 
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [38]:
m1 = np.array([[1,2,],[3,4]])
m2 = np.array([[2,4],[5,6]])
print(f'dot product:\n{m1@m2}')


dot product:
[[12 16]
 [26 36]]


In [40]:
m3 = np.array([[1,4,],[4,6,]])
m4 = m1@m3
print(f'm4: \n{m4}')
print(f'trace: {np.trace(m4)}')


m4: 
[[ 9 16]
 [19 36]]
trace: 45


In [45]:
m = np.array([[1,1,0],[0,2,1],[0,0,3]])
print(m)
val, vec = np.linalg.eig(m)
print(val)
print(vec)

[[1 1 0]
 [0 2 1]
 [0 0 3]]
[1. 2. 3.]
[[1.         0.70710678 0.33333333]
 [0.         0.70710678 0.66666667]
 [0.         0.         0.66666667]]


In [47]:
print(m@vec)
print(vec*val)

[[1.         1.41421356 1.        ]
 [0.         1.41421356 2.        ]
 [0.         0.         2.        ]]
[[1.         1.41421356 1.        ]
 [0.         1.41421356 2.        ]
 [0.         0.         2.        ]]


## IV. Mission:

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [22]:
from typing import Union
def get_L2_norm(x: np.ndarray) -> Union[float, np.ndarray]:
    return np.linalg.norm(x)

x = np.arange(5)
print(f'L2 norm: {get_L2_norm(x)}')


L2 norm: 5.477225575051661


### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [24]:
def is_singular(x: np.ndarray) -> bool:
    return np.linalg.det(x) == 0

singular_mat = np.array([[1,2],[3,4]])
nonsingular_mat = np.array([[1,4,],[2,8]])
print(is_singular(singular_mat), is_singular(nonsingular_mat))

False True
