# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

In [1]:
import numpy as np

## II. Numpy로 연산하기

In [2]:
x = np.array([1, 2, 3])
c = 5

print('더하기 : {}'.format(x + c))
print('빼기 : {}'.format(x - c))
print('곱하기 : {}'.format(x * c))
print('나누기 : {}'.format(x / c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


In [3]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print('더하기 : {}'.format(y + z))
print('빼기 : {}'.format(y - z))
print('곱하기 : {}'.format(y * z))
print('나누기 : {}'.format(y / z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


In [4]:
W = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(W[0,0])
print(W[2,3])
print(W)

1
12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## III. Numpy로 선형대수 지식 끼얹기

In [5]:
W = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# get 2,3 6,7
print(W[0:2,1:3])
print(W[1,1:3])
print(W[0:2,])

[[2 3]
 [6 7]]
[6 7]
[[1 2 3 4]
 [5 6 7 8]]


In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0, 1, 0])
x = x[:, None]
print(x)
print(a+x)

[[0]
 [1]
 [0]]
[[1 2 3]
 [5 6 7]
 [7 8 9]]


In [9]:
y = np.array([0, 1, -1])

print(a * y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


In [10]:
t = np.array([1,2,3])
t = t[:, None]
u = np.array([2, 0, -2])
print(t)
print(t + u)

[[1]
 [2]
 [3]]
[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


In [11]:
np.zeros([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.diag([2,4])

array([[2, 0],
       [0, 4]])

In [14]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [15]:
#항등행렬
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [16]:
#행렬곱
mat_1 = np.array([[1,4],[2,3]])
mat_2 = np.array([[7,9],[0,6]])

print(mat_1.dot((mat_2)))
print(mat_1 @ mat_2)

[[ 7 33]
 [14 36]]
[[ 7 33]
 [14 36]]


In [17]:
# trace -> main diagonal의 합
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
arr.trace()
np.eye(2, dtype=int).trace()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

# Linear Algebra
행렬식 (determinant)

linag = Linear Algebra

In [18]:
arr_2 = np.array([[2,3],[1,6]])
print(arr_2)
print(np.linalg.det(arr_2))

[[2 3]
 [1 6]]
9.000000000000002


In [19]:
arr_3 = np.array([[1,4,7],[2,5,8],[3,6,9]])
print(arr_3)
print(np.linalg.det(arr_3))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
0.0


# 역행렬
행렬 A에 대해 AB = BA = I를 만족하는 행렬 B=A^-I

In [20]:
mat = np.array([[1,4],[2,3]])
print(mat)
mat_inv = np.linalg.inv(mat)
print(mat_inv)
print(mat@mat_inv)

[[1 4]
 [2 3]]
[[-0.6  0.8]
 [ 0.4 -0.2]]
[[1. 0.]
 [0. 1.]]


# 고유값과 고유벡터(eigenvalue and eigenvector)
정방행렬 A에 대해 Ax=$\lambda x$를 만족하는 상수 $\lambda$와 이에 대응하는 벡터

In [21]:
mat = np.array([[2,0,-2],[1,1,-2],[0,0,1]])
print(mat)
np.linalg.eig(mat) # return lambda, eigenvector

[[ 2  0 -2]
 [ 1  1 -2]
 [ 0  0  1]]


(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

In [22]:
eig_val, eig_vec = np.linalg.eig(mat)
eig_val

array([1., 2., 1.])

In [23]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [24]:
mat @ eig_vec[:,0]

array([0., 1., 0.])

In [25]:
eig_val[0] * eig_vec[:, 0]

array([0., 1., 0.])

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [4]:
import numpy as np
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat = np.array([1,2,3])
np.linalg.norm(mat)

3.7416573867739413

### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [5]:
def is_singular(mat):
    if np.linalg.det(mat):
        return False
    return True
mat1 = [[1,2],[3,4]]
print(is_singular(mat1))
mat2 = [[1,2],[1,2]]
print(is_singular(mat2))

False
True
