# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

In [2]:
import numpy as np

## II. Numpy로 연산하기

## Vector와 Scalar 사이의 연산
벡터의 각 원소에 대해서 연산을 진행

$$ x = \begin{pmatrix}1\\2\\3\end{pmatrix} \quad c = 5$$

In [7]:
x = np.array([1, 2, 3])
c = 5

print("더하기 : {}".format(x + c))
print("빼기 : {}".format(x - c))
print("곱하기 : {}".format(x * c))
print("나누기 : {}".format(x / c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산

벡터의 **같은 인덱스**끼리 연산이 진행!!

$$ y = \begin{pmatrix}1\\3\\5\end{pmatrix} \quad z = \begin{pmatrix}2\\9\\20\end{pmatrix}$$

In [9]:
y, z = np.array([1, 3, 5]), np.array([2, 9, 20])
## np.array() 의 인자는 list or tuple
print("더하기 : {}".format(y + z))
print("빼기 : {}".format(y - z))
print("곱하기 : {}".format(y * z))
print("나누기 : {}".format(y / z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


## Array Indexing

Python의 리스트와 유사하게 진행
$$ W = \begin{pmatrix} 1 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8 \\ 9 & 10 & 11 & 12 \end{pmatrix} $$

In [27]:
W = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(W[0, 0])
print(W[2, 3])
print(W)

W[:, 0] = [1,2, 4]
W

1
12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  2,  3,  4],
       [ 2,  6,  7,  8],
       [ 4, 10, 11, 12]])

## Array Slicing

Python의 리스트와 유사하게 진행

In [31]:
W = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

##2, 3, -> 행: 인덱스 0~1 -> [0:2]
##6, 7 -> 열: 인덱스 1~2 -> [1:3]
    
W[0:2, 1:3]

array([[2, 3],
       [6, 7]])

[a:b]

[:b] - 맨 처음부터 b까지 (\~b-1)  
[a:] - a부터 맨 마지막까지 (a\~)  
[:] - 전체

In [33]:
W[0:2, 0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
W[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
W[0:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
W[: ,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

## Array Broadcasting

기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능  
하지만 만약에 피연산자가 연산 가능하도록 변환이 가능하다면 연산이 가능하다.  
이를 Broadcasting이라고 한다.

### 1. M by N, M by 1

In [43]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([0, 1, 0])

x = x[:, None] # x를 transpose
print(a + x)

[[1 2 3]
 [5 6 7]
 [7 8 9]]


### 2. M by N, 1 by N

In [47]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([0, 1, 0])

y = np.array([0, 1, -1])

print(a * y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


### 3. M by 1, 1 by N

In [50]:
t = np.array([1, 2, 3]) # 열벡터로 바꿔야함
t = t[:, None] # Transposed

u = np.array([2, 0, -2])

print(t + u)

# M by N 행렬이 나옴

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


## III. Numpy로 선형대수 지식 끼얹기

### A. basics

### 영백터(행렬)

- 원소가 모두 0인 벡터(행렬)
- `np.zeros(dim)`을 통해 생성, dim은 값, 혹은 튜플 (, )

In [54]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### 일벡터(일행렬)
- 원소가 모두 1인 벡터(행렬)
- `np.ones(dim)`을 통해 생성, dim은 값, 혹은 튜플 (, )

In [55]:
np.ones((3, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### 대각행렬(diagonal matrix)
- Main diagonal을 제외한 성분이 0인 행렬
- `np.diag((main_diagonal))`을 통해 생성

In [56]:
np.diag((1,2,3,4,5))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

### 항등행렬(identity matrix)
- Main diagonal이 1인 대각행렬
- `np.eye(n, (dtype))`를 사용, data type을 인자로 넘겨줄 수 있다. (n, dtype=int), default는 float (dtype = int, uint, float, complex)

In [62]:
np.eye(2, dtype = "int")

array([[1, 0],
       [0, 1]])

### 행렬곱(dot product)
- 행렬간의 곱연산
- `np.dot() or @` 사용

In [64]:
mat_1 = np.array([[1, 4], [2, 3]])
mat_2 = np.array([[7, 9], [0, 6]])

print(mat_1.dot(mat_2))
print(mat_1 @ mat_2)

[[ 7 33]
 [14 36]]
[[ 7 33]
 [14 36]]


In [65]:
mat_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat_2 = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
print(mat_1.dot(mat_2))
print(mat_1 @ mat_2)

[[ 330  396  462]
 [ 726  891 1056]
 [1122 1386 1650]]
[[ 330  396  462]
 [ 726  891 1056]
 [1122 1386 1650]]


### 트레이스(trace)
- Main diagonal의 합 \-  $ \Sigma a_{ii}$
- np.trace()를 사용

In [67]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr.trace()

np.eye(2).trace()

2.0

### 행렬식(determinant)
- 행렬을 대표하는 값들 중 하나
- 선형변환 과정에서 Vector의 Scaling 척도
- `np.linalg.det()`

In [73]:
arr_2 = np.array([[2, 3], [1, 6]])

arr_2

np.linalg.det(arr_2)

9.000000000000002

In [71]:
arr_3 = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])

np.linalg.det(arr_3)

0.0

### 역행렬(inverse matrix)
- 행렬 A에 대해 AB = BA = I를 만족하는 행렬 $ B=A^-1 $
- `np.linalg.inv()`로 구함

In [77]:
mat = np.array([[1, 4], [2, 3]])

mat_inv = np.linalg.inv(mat)

print(mat_inv)
mat @ mat_inv

[[-0.6  0.8]
 [ 0.4 -0.2]]


array([[1., 0.],
       [0., 1.]])

### 고유값과 고유벡터(eigenvalue and eigenvector)
- 정방행렬(nxn) A에 대해 $ Ax = \lambda x$ 를 만족하는 $\lambda$와 $x$ 를 고유값과 고유벡터라 한다.
- `np.linalg.eig()`로 계산

In [78]:
mat = np.array([[2, 0, -2], [1, 1, -2], [0, 0, 1]])

mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [79]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

In [80]:
eig_val, eig_vec = np.linalg.eig(mat)
eig_val

array([1., 2., 1.])

In [82]:
mat @ eig_vec[:, 0] # Ax

array([0., 1., 0.])

In [83]:
eig_val[0] * eig_vec[:, 0]# (lambda)x

array([0., 1., 0.])

In [87]:
size = len(eig_val)
ret = [[mat @ eig_vec[:, i], eig_val[i]*eig_vec[:, i]] for i in range(size)]
ret

[[array([0., 1., 0.]), array([0., 1., 0.])],
 [array([1.41421356, 1.41421356, 0.        ]),
  array([1.41421356, 1.41421356, 0.        ])],
 [array([0.89442719, 0.        , 0.4472136 ]),
  array([0.89442719, 0.        , 0.4472136 ])]]

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [92]:
import math
y = np.array([-1,2,4])

def get_L2_norm(vec):
    return math.sqrt(sum(vec ** 2))

get_L2_norm(y)

4.58257569495584

### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [125]:
import scipy, scipy.linalg
mat = np.array([[2, 2, 2], [-1/2, 1/2, 1/2], [-2,-2, -2]])
# mat = np.array([[1, 2], [3, 4]])


def is_singular(mat):
    p, l, u = scipy.linalg.lu(mat)
    if 0 in u.diagonal():
        return True
    return False

is_singular(mat)

True

In [126]:
#특이값 분해(Singular Value Decomposition, SVD)

if is_singular(mat):
    u, d, v = np.linalg.svd(mat)
u, d, v

print(u @ d @ v)

[1.03842617 0.01590036 4.86532818]
