# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

## II. Numpy로 연산하기

## III. Numpy로 선형대수 지식 끼얹기

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [2]:
import numpy as np

In [28]:
arr = np.array([1, 3, 5])

arr

array([1, 3, 5])

In [22]:
# 수식에 대입 ( 답 확인용)
np.sqrt(1**2 + 3**2 + 5**2)

5.916079783099616

In [29]:
# L2 norm은 Euclidean Distance를 의미 -> 거리의 정의
## 즉, 두 개의 벡터의 각 원소를 빼고, 제곱을하고, 합치고, 루트를 씌운 것
### L2 norm의 공식을 이용

def get_L2_norm_1(arr):
  sum = 0
  answer = 0
  for i in n:
    sum += i ** 2
  
  answer = np.sqrt(sum)
  return answer

print(get_L2_norm_1(arr))

5.916079783099616


In [30]:
## 깔끔하게 정리

def get_L2_norm_2(arr):
  return np.sqrt(sum(map(lambda x: x**2, arr)))

print(get_L2_norm_2(arr))


5.916079783099616


In [31]:
## numpy의 linalg.norm 이용
def get_L2_norm_3(arr):
  return np.linalg.norm(arr)

print(get_L2_norm_3(arr))

5.916079783099616


### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [ ]:
# singular matrix는 A의 역행렬이 존재하지 않는다는 의미 
## det(A) = ad - bc = 0 이라는 것

In [40]:
# non-singular 한 예시
arr_2n = np.array([[1, 2], [3, 4]])

arr_2n

array([[1, 2],
       [3, 4]])

In [41]:
# singular 한 예시
arr_2s = np.array([[1, 2], [2, 4]])

arr_2s

array([[1, 2],
       [2, 4]])

In [42]:
def is_singular(arr):
  det = np.linalg.det(arr)
  return True if det ==0 else False

is_singular(arr_2n)

False

In [43]:
is_singular(arr_2s)

True