# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

In [2]:
import numpy as np

**list**

In [13]:
L = range(1000)

%timeit [i**2 for i in L]

223 µs ± 2.47 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


**numpy.array**

In [10]:
N = np.arange(1000)

%timeit N ** 2

1.6 µs ± 8.16 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [14]:
arr = np.array([1, 2, 3])

arr

array([1, 2, 3])

In [16]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr.shape

(3,)

In [19]:
arr_2d.shape

(3, 3)

## II. Numpy로 연산하기

### Vector와 Scalar 사이의 연산
벡터의 각 원소에 대해서 연산을 진행

$x=\begin{pmatrix}1\\2\\3\end{pmatrix}\hspace{1em}c=5$

In [4]:
x = np.array([1,2,3])
c = 5

print(f"더하기 : {x + c}")
print(f"빼기 : {x - c}")
print(f"곱하기 : {x * c}")
print(f"나누기 : {x / c}")

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산

벡터의 **같은 인덱스**끼리 연산이 진행!!

$y=\begin{pmatrix}1\\3\\5\end{pmatrix}\hspace{1em}z=\begin{pmatrix}2\\9\\20\end{pmatrix}$

In [6]:
y = np.array([1,3,5])
z = np.array([2,9,20])

print(f"더하기 : {y + z}")
print(f"빼기 : {y - z}")
print(f"곱하기 : {y * z}")
print(f"나누기 : {y / z}")

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


## Array Indexing

Python의 리스트와 유사하게 진행

$W=\begin{pmatrix}1&2&3&4\\5&6&7&8\\9&10&11&12\end{pmatrix}$

In [7]:
W = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

W[0, 0]

1

In [8]:
W[2, 3]

12

In [9]:
# 7을 가져오려면?

W[1, 2]

7

## Array Slicing

Python의 리스트와 유사하게 진행

$W=\begin{pmatrix}1&2&3&4\\5&6&7&8\\9&10&11&12\end{pmatrix}$

In [11]:
W = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

W[0:2, 1: 3]

array([[2, 3],
       [6, 7]])

In [13]:
print(W[0:2, 0:4])
print(W[0:2])
print(W[0:2, :])

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [14]:
print(W[0:3, 2:4])
print(W[:, 2:4])

[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 3  4]
 [ 7  8]
 [11 12]]


## Array의 Broadcasting

기본적으로 같은 Type의 data에 대해서만 연산이 적용가능

하지만 만약 피연산자가 연산 가능하도록 변환이 가능하다면 연산이 가능.  
이를 **Broadcasting**이라고 한다.

### 1. M by N, M by 1 

In [16]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0,1,0])

x = x[:, None] # x를 전치
print(x)

print(a + x)

[[0]
 [1]
 [0]]
[[1 2 3]
 [5 6 7]
 [7 8 9]]


### 2. M by N, 1 by N

In [18]:
y = np.array([0,1,-1])

print(a * y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


### 3. M by 1, 1 by N

In [24]:
t = np.array([1,2,3])  # 열벡터로 바꿔줘야 함!
t = t[:, None]  # Transpose

u = np.array([2,0,-2])

print(t + u)

'''
1 1 1     2 0 -2
1 1 1 + 2 0 -2
1 1 1     2 0 -2
'''

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


## III. Numpy로 선형대수 지식 끼얹기

### A. Basics

### 영벡터(행렬)
- 원소가 모두 0인 벡터(행렬)
- `np.zeros(dim)`을 통해 생성, dim은 값 혹은 튜플(, )

In [27]:
np.zeros(3)

array([0., 0., 0.])

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### 일벡터(행렬)
- 원소가 모두 1인 벡터(행렬)
- `np.ones(dim)`을 통해 생성, dim은 값 혹은 튜플(,)

In [33]:
np.ones(2)

array([1., 1.])

In [35]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 대각행렬
- main diagonal을 제외한 성분이 0인 행렬
- `np.diag(main_diagonal)`을 통해 생성

In [36]:
np.diag((2, 4))

array([[2, 0],
       [0, 4]])

In [38]:
np.diag((1, 3, 5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### 항등행렬
- main diagonal이 1인 대각행렬
- `np.eye(n[, dtype=float])`를 사용

*dtype: data type, (dtype=int, uint, float, complex, ...)*

In [39]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 행렬곱
- 행렬간에 정의되는 곱 연산
- `np.dot()`, `@` 사용

In [42]:
mat_1 = np.array([[1, 4], [2, 3]])
mat_2 = np.array([[7, 9], [0, 6]])

mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

In [43]:
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

## B. Furthermore

### 트레이스
- main diagonal의 합
- `np.trace()`를 사용

In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr.trace()

15

In [46]:
np.eye(2, dtype=int).trace()

2

### 행렬식
$ad-bc$

- 행렬을 대표하는 값들 중 하나 → 선형변환
- 선형변환 과정에서 Vector의 Scaling 척도
- `np.linalg.det()` 으로 계산

In [48]:
arr_2 = np.array([[2, 3], [1, 6]])

np.linalg.det(arr_2)

9.000000000000002

In [49]:
arr_3 = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])

np.linalg.det(arr_3)

0.0

### 역행렬
$\begin{pmatrix}a&b\\c&d\end{pmatrix} = {\Large\frac{1}{ad-bc}}\begin{pmatrix}d&-b\\-c&a\end{pmatrix}$

- 행렬 A에 대해 $AB = BA = I$ 를 만족하는 행렬 $B (= A^{-1})$
- `np.linalg.inv()`을 사용

In [51]:
mat = np.array([[1, 4], [2, 3]])

mat

array([[1, 4],
       [2, 3]])

In [53]:
mat_inv = np.linalg.inv(mat)

mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [54]:
mat @ mat_inv

array([[1., 0.],
       [0., 1.]])

### 고유값과 고유벡터
$Ax = \lambda x \hspace{1em}\Rightarrow \hspace{1em} (A-\lambda I)x = 0$

- 정방행렬 $A_{n\times n}$에 대하여 $Ax=\lambda x$를 만족하는 $\lambda$와 x를 각각 고유값과 고유벡터라고 한다.
- `np.linalg.eig()`로 계산

In [5]:
mat = np.array([[2, 0, -2], [1, 1, -2], [0, 0, 1]])

mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [6]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

**Validation**

In [7]:
eig_val, eig_vec = np.linalg.eig(mat)

eig_val

array([1., 2., 1.])

In [8]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [14]:
mat @ eig_vec[:, 0] # Ax

array([0., 1., 0.])

In [12]:
eig_val[0] * eig_vec[:, 0] # (lambda)x

array([0., 1., 0.])

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [15]:
import numpy as np

mat = np.array([1,2,3,4])

def get_L2_norm(mat):
    return np.linalg.norm(mat, ord=2)

print(get_L2_norm(mat))
# 5.477225575051661

5.477225575051661


### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [16]:
import numpy as np

mat_1 = np.array([[1,2],[3,4]])
mat_2 = np.array([[1,2],[2,4]])

def is_singular(mat):
    return True if np.linalg.det(mat) == 0 else False

print(is_singular(mat_1))
# False
print(is_singular(mat_2))
# True

False
True
