# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

In [2]:
import numpy as np

## II. Numpy로 연산하기

Vector와 Scalar 사이의 연산  
(format을 활용할 것! 문자열 {}안에 값을 넣어줌  
format 사용하는 이유? .format()안에 변수를 넣어줄 수 있다.)

In [3]:
x = np.array([1,2,3])
c = 5

print("더하기: {}".format(x+c))
print("빼기: {}".format(x-c))
print("곱하기: {}".format(x*c))
print("나누기: {}".format(x/c))

더하기: [6 7 8]
빼기: [-4 -3 -2]
곱하기: [ 5 10 15]
나누기: [0.2 0.4 0.6]


벡터의 각 원소에 대해 연산을 실행하는 것을 확인 가능

In [15]:
y = np.array([1,3,5])
z = np.array([2,9,20])

print("더하기: {}".format(y+z))
print("빼기: {}".format(y-z))
print("곱하기: {}".format(y*z))
print("나누기: {}".format(y/z))

더하기: [ 3 12 25]
빼기: [ -1  -6 -15]
곱하기: [  2  27 100]
나누기: [0.5        0.33333333 0.25      ]


### Vector와 Vector 사이의 연산
벡터의 **같은 인덱스** 끼리 연산이 진행!  
참고! array의 인자는 하나

### Array indexing
Python의 리스트와 유사하게 진행  
단, numpy에서 인덱스 갖고 오려면 [a][b]가 아니라 -> [a, b]  

In [5]:
W = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(W)
W[0,0]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


1

In [6]:
W[2,3]

12

In [7]:
# Q: 7가져오기
W[1,2]

7

### Array slicing
Python의 리스트와 유사하게 진행

In [8]:
W = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

#[2, 3] [6, 7] 가져오기
#2,3 행: 인덱스 0~1
#6,7 열: 인덱스 1~2

W[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [9]:
# [a:b]
# [:b] 처음부터 b-1까지
# [a: ] a부터 끝까지
W[0:2, 0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
W[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
W[0:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
W[0:3, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [13]:
W[:, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

### Array Broadcasting
Numpy가 연산을 진행하는 특수한 방법!  
기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능  
하지만 만약에 피연산자가 연산 가능하도록 변환이 가능하다면 연산이 가능하다.  
이를 **Broadcasting**이라 한다.

### 1. M by N, M by 1

In [20]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0,1,0])

x = x[: None]

print(a+x)

[[1 3 3]
 [4 6 6]
 [7 9 9]]


### 2. M by N, 1 by N(행벡터) -> 1xN이 NxN으로

In [21]:
y = np.array([0,1,-1])

print(a*y)

[array([[ 0,  2, -3],
       [ 0,  5, -6],
       [ 0,  8, -9]])]


### 3. M by 1(열벡터), 1 by N(행벡터) -> M by N M by N연산으로 

In [26]:
t = np.array([1,2,3])
t = t[:, None]
u = np.array([2,0,-2])
print(t+u)


#1 1 1   2 0 -2
#2 2 2 + 2 0 -2
#3 3 3   2 0 -2

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


## III. Numpy로 선형대수 지식 끼얹기

### A. basics

### 영백터(행렬)   

- 원소가 모두 0인 벡터(행렬)
- `p.zeros(dim)`을 통해 생성, dim은 값, 혹은 튜플 (, )

In [31]:
np.zeros(1)

array([0.])

In [32]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 일벡터(일행렬)  

- 원소가 모두 1인 벡터(행렬)
- `np.ones(dim)`을 통해 생성, dim은 값, 튜플(,)


In [33]:
np.ones(1)

array([1.])

In [34]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### 대각행렬  

- Main diagonal을 제외한 성분이 0인 행렬
- `np.diag(main_diagonals)`을 통해 생성할 수 있음

In [35]:
np.diag([2,4])

array([[2, 0],
       [0, 4]])

In [36]:
np.diag([1,3,5])

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### 항등행렬

- Main diagonal이 1인 diagonal matrix(대각행렬)
- `np.eye(n, (dtype = int, uint, float, complex, ...))`를 사용

In [39]:
np.eye(2).dtype
np.eye(2, dtype = int)

array([[1, 0],
       [0, 1]])

### 행렬곱  

- 행렬간에 정의되는 곱 연산(dot product)
- `np.dot()`, `@`를 사용

In [40]:
mat_1 = np.array([[1,4], [2,3]])
mat_2 = np.array([[7,9], [0,6]])

mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

In [41]:
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

### B.

### 트레이스

- Main Diagonal의 합
- `np.trace()`를 사용

In [43]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr.trace()

15

In [45]:
np.eye(2, dtype = int)

array([[1, 0],
       [0, 1]])

In [46]:
np.eye(2, dtype = int).trace()

2

### determinant (행렬식)

- 행렬을 대표하는 값 중 하나
- 선형변환 과정에서 vector의 scaling 척도
- `np.linalg.det()`으로 계산

linalg: linear algebra`

In [48]:
arr_2 = np.array([[2,3], [1,6]])
arr_2

array([[2, 3],
       [1, 6]])

In [49]:
np.linalg.det(arr_2)

9.000000000000002

In [50]:
arr_3 = np.array([[1,4,7], [2,5,8], [3,6,9]])
arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [51]:
np.linalg.det(arr_3)

0.0

0이다 = full rank가 아니다 = 선형종속관계가 존재한다 = singluar

### 역행렬

- 행렬 A에 대해서 AB = BA = I를 만족하는 행렬 B
- `np.linalg.int()`을 사용

In [52]:
mat = np.array([[1,4], [2,3]])
mat

array([[1, 4],
       [2, 3]])

In [53]:
mat_inv = np.linalg.inv(mat)
mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [54]:
mat@mat_inv

array([[1., 0.],
       [0., 1.]])

### C.

### 고유값과 고유벡터   
선형변환하는 과정에서 어떤 벡터는 방향이 변하지 않고 크기만 변하는 경우가 생김  
왜? 같은 span에 위치해서!  
이 span되는 비율을 고유값  
span된 영역에 대한 벡터를 고유벡터  
  
이걸 구하기 위해선 (A-$\lambda$I)X = 0에서
x가 0이 되어야하는데, 영행렬이 아니라면 
$\lambda$값을 구하기 위해서 det(A-$\lambda$I)을 구해서 계산한다  

- 정방행렬(nxn) A에 대해서 $Ax = \lambda x$을 만족하는 $\lambda$와 x를 각각 고유값과 고유벡터라고 한다.  
- `np.linalg.eig()`로 계산

In [57]:
mat = np.array([[2,0,-2],[1,1,-2],[0,0,1]])
mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [58]:
np.linalg.eig(mat)

(array([1., 2., 1.]), array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

$\lambda$(고유값) 1에 대응되는 고유벡터는 [0, 1, 0]  
$\lambda$(고유값) = [1,2,1]

Validation

In [59]:
eig_val, eig_vec = np.linalg.eig(mat)

eig_val

array([1., 2., 1.])

In [61]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [63]:
mat @ eig_vec[:,0] #Ax

array([0., 1., 0.])

In [64]:
eig_val[0] @ eig_vec[:, 0] #(lambda) x
#ValueError: Scalar operands are not allowed, use '*' instead
#충분한 공간이 없어요!

ValueError: Scalar operands are not allowed, use '*' instead

In [65]:
eig_val[0] * eig_vec[:, 0]

array([0., 1., 0.])

나머지도 마찬가지야!

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [76]:
def get_L2_norm(arr):
    number = 0
    number = sum(np.square(arr))
    return np.sqrt(number)

In [78]:
a = np.array([1,2,-3])

In [82]:
get_L2_norm(a)

3.7416573867739413

- `np.linalg.norm(arr, ord, axis)`이 존재하나 dim = 1 일땐 사용할 수 없음
- 범용함수(universal functions) 사용

### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [87]:
def is_singular(arr):
    if np.linalg.det(arr) == 0.0:
        return True
    else:
        return False

In [88]:
mat_1 = np.array([[1,2],[3,4]])
is_singular(mat_1)

False

In [90]:
mat_2 = np.array([[1,1],[1,1]])
is_singular(mat_2)

True