# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

In [3]:
import numpy as np

## II. Numpy로 연산하기

### Vector와 Scalar 사이의 연산
벡터의 각 원소에 대해서 연산을 진행

In [11]:
x = np.array([1, 2, 3])
c = 5

print("더하기 : {}".format(x + c))
print("빼기 : {}".format(x - c))
print("곱하기 : {}".format(x * c))
print("나누기 : {}".format(x / c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산
벡터의 **같은 인덱스**끼리 연산이 진행

In [14]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print("더하기 : {}".format(y + z))
print("빼기 : {}".format(y - z))
print("곱하기 : {}".format(y * z))
print("나누기 : {}".format(y / z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


### Array Indexing
python의 리스트와 유사하게 진행

In [18]:
W = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

W[0, 0]

1

In [19]:
W[2, 3]

12

In [20]:
# 7을 가져오려면?

W[1, 2]

7

### Array Slicing

Python의 리스트와 유사하게 진행

In [27]:
W = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

W[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [34]:
W[1:, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
W[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
W[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Array Broadcasting
Numpy가 연산을 진행하는 특수한 방법!

기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능하나.

하지만 Numpy는 피연산자가 연산 가능하도록 변환을 시켜준다.

#### 1. M * N, M * 1

In [39]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([0, 1, 0])

x = x[:, None]
print(a + x)

[[1 2 3]
 [5 6 7]
 [7 8 9]]


#### 2. M * N, 1 * N

In [38]:
y = np.array([0, 1, -1])

print(a * y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


#### 3. M * 1, 1 * N

In [42]:
# 열벡터
t = np.array([1, 2, 3])
t = t[:, None]

#행벡터
u = np.array([2, 0, -2])

print(t + u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


## III. Numpy로 선형대수 지식 끼얹기

### A. Basics

### 영벡터(행렬)

- 원소가 모두 0인 벡터(행렬)
- `np.zeros(dim)`을 통해 생성, dim은 값, 혹은 튜플 (,)

In [44]:
np.zeros(2)

array([0., 0.])

In [48]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### 일벡터(행렬)

- 원소가 모두 1인 벡터(행렬)
- `np.ones(dim)`을 통해 생성, dim은 값, 튜플(,)

In [45]:
np.ones(2)

array([1., 1.])

In [49]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 대각행렬

- Main Diagonal을 제외한 성분이 0일 행렬
- `np.diag((main_diagnals))`을 통해 생성할 수 있음.

In [46]:
np.diag((2, 4))

array([[2, 0],
       [0, 4]])

In [47]:
np.diag((1, 3, 5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### 항등행렬

- main diagonal == 1인 diagonal matrix(대각행렬)
- `np.eye(n, (dtype=int, uint, float, complex, ...))`을 통해 생성

In [61]:
np.eye(2).dtype

dtype('float64')

In [62]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### 행렬곱

- 행렬간에 정의되는 곱 연산(dot product)
- `np.dot()` 또는 `@`을 사용

In [63]:
mat_1 = np.array([[1, 4], [2, 3]])
mat_2 = np.array([[7, 9], [0, 6]])

mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

In [64]:
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

### 트레이스

- Main diagonal의 합
- np.trace()를 사용

In [67]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
np.trace(arr)

15

In [71]:
arr.trace()

15

In [72]:
np.eye()

TypeError: eye() missing 1 required positional argument: 'N'

### 행렬식

- 행렬을 대표하는 값들 중 하나
- 선형변환 과정에서 Vector의 Scaling 척도
- `np.linalg.det()`으로 계산

In [80]:
arr_2 = np.array([[2, 3], [1, 6]])

arr_2

array([[2, 3],
       [1, 6]])

In [74]:
np.linalg.det(arr_2)

9.000000000000002

In [77]:
arr_3 = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])

arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [79]:
np.linalg.det(arr_3)

0.0

### 역행렬

- 행렬 A에 대해 AB = BA = I을 만족하는 행렬 B = A^-1
- `np.linalg.inv()`로 계산

In [82]:
mat = np.array([[1, 4], [2, 3]])

mat

array([[1, 4],
       [2, 3]])

In [84]:
mat_inv = np.linalg.inv(mat)

mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [85]:
mat @ mat_inv

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

### 고유값과 고유벡터

- 정방행렬(nxn) A에 대해 $Ax = \lambda x$를 만족하는 상수 $\lambda$와 x를 각각 고유값과 고유벡터라 한다.
- `np.linalg.eig()`로 계산

In [88]:
mat = np.array([[2, 0, -2], [1, 1, -2], [0, 0, 1]])

mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [89]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

#### Validation

In [91]:
eig_val, eig_vec = np.linalg.eig(mat)

eig_val

array([1., 2., 1.])

In [92]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [93]:
mat @ eig_vec[:, 0]

array([0., 1., 0.])

In [94]:
eig_val[0] * eig_vec[:, 0]

array([0., 1., 0.])

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [108]:
def get_L2_norm(vec):
    answer = 0
    for elem in vec:
        answer += elem ** 2
    return answer ** 0.5

In [111]:
vec = np.array([3, 4])

print(get_L2_norm(vec))

5.0


### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [100]:
def is_singular(mat):
    try:
        np.linalg.inv(mat)
        return False
    except:
        return True

In [103]:
# Singular
mat_1 = np.array([[1, 1, 0], [2, 2, 0], [0, 0, 1]])

print(is_singular(mat_1))

True


In [104]:
# non-singular
mat_2 = np.array([[1, 0, 0], [2, 2, 0], [0, 0, 1]])

print(is_singular(mat_2))

False
