# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

### numpy.array

numpy의 Container, array

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [3]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print(arr.shape)
print(arr_2d.shape)

(3,)
(3, 3)


## II. Numpy로 연산하기

### vector와 scalar 사이의 연산

벡터의 각 원소에 대해서 연산을 진행

$$ x = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}, c = 5 $$

In [10]:
x = np.array([1,2,3])
c = 5
print(f"더하기 : {x+c}")
print(f"빼기 : {x-c}")
print(f"곱하기 : {x*c}")
print(f"나누기 : {x/c}")

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### vector와 vector사이의 연산

벡터의 **같은 index**끼리 연산이 진행된다.

$$y = \begin{bmatrix} 1 \\ 3 \\ 5 \end{bmatrix}, z = \begin{bmatrix} 2 \\ 9 \\ 20 \end{bmatrix}$$

In [13]:
y = np.array([1,3,5])
z = np.array([2,9,20])
print(f"더하기 : {y+z}")
print(f"빼기 : {y-z}")
print(f"곱하기 : {y*z}")
print(f"나누기 : {y/z}")

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


### Array의 Indexing

array에서 특정 위치의 원소를 가져오고 싶다면? -> Python List와 유사하게 진행

$$w = \begin{bmatrix} 1& 2& 3& 4 \\ 5& 6& 7& 8 \\ 9 & 10 & 11 & 12 \end{bmatrix}$$

In [15]:
w = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(w[0][0]) # 1
print(w[2,3]) # 12

1
12


### Array의 Slicing

array에서 특정 범위의 원소들을 가져오고 싶다면? -> Python list와 유사하게 진행

In [22]:
# [[2,3],[6,7]] 가져오고 싶을때
# 행 인덱스 0~1 : [0:2] // 열인덱스 1~2 : [1:3]
print(w[0:2, 1:3])
# 첫행 2개 가져올때
print(w[0:2, 0:4])
print(w[:2])
print(w[:2,:])

[[2 3]
 [6 7]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [23]:
# 뒤에 열 2개 가져올때
print(w[0:3, 2:4])
print(w[:,2:4])

[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 3  4]
 [ 7  8]
 [11 12]]


### Array의 Broadcasting

기본적으로 같은 type의 Data에 대해서만 연산이 적용 가능  
하지만 만약에 피연산자가 연산가능하도록 변환이 가능하다면 연산 가능  
이를 **Broadcasting**이라고 합니다.

$$A = \begin{bmatrix} 1& 2& 3 \\ 4& 5& 6 \\ 7& 8 & 9 \end{bmatrix}, m = \begin{bmatrix} 3 \\ 2 \\ 1 \end{bmatrix}$$

#### 1. MxN, Mx1

In [32]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
m = np.array([[3],[2],[1]])

print(f"더하기 : \n{A+m}")
print(f"빼기 : \n{A-m}")
print(f"곱하기 : \n{A*m}")
print(f"나누기 : \n{A/m}")

더하기 : 
[[ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]
빼기 : 
[[-2 -1  0]
 [ 2  3  4]
 [ 6  7  8]]
곱하기 : 
[[ 3  6  9]
 [ 8 10 12]
 [ 7  8  9]]
나누기 : 
[[0.33333333 0.66666667 1.        ]
 [2.         2.5        3.        ]
 [7.         8.         9.        ]]


#### 2. MxN, 1XM

$$A = \begin{bmatrix} 1& 2& 3 \\ 4& 5& 6 \\ 7& 8 & 9 \end{bmatrix}, n = \begin{bmatrix} 3 & 2 & 1 \end{bmatrix}$$

In [31]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
n = np.array([3,2,1])
# n = m[:, None] # m을 transpose

print(f"더하기 : \n{A+n}")
print(f"빼기 : \n{A-n}")
print(f"곱하기 : \n{A*n}")
print(f"나누기 : \n{A/n}")

더하기 : 
[[ 4  4  4]
 [ 7  7  7]
 [10 10 10]]
빼기 : 
[[-2  0  2]
 [ 1  3  5]
 [ 4  6  8]]
곱하기 : 
[[ 3  4  3]
 [12 10  6]
 [21 16  9]]
나누기 : 
[[0.33333333 1.         3.        ]
 [1.33333333 2.5        6.        ]
 [2.33333333 4.         9.        ]]


#### 3. Mx1, 1XM

$$m = \begin{bmatrix} 3 \\ 2 \\ 1 \end{bmatrix}, n = \begin{bmatrix} 3 & 2 & 1 \end{bmatrix}$$

In [30]:
m = np.array([[3],[2],[1]])
n = np.array([3,2,1])

print(f"더하기 : \n{m+n}")
print(f"빼기 : \n{m-n}")
print(f"곱하기 : \n{m*n}")
print(f"나누기 : \n{m/n}")

더하기 : 
[[6 5 4]
 [5 4 3]
 [4 3 2]]
빼기 : 
[[ 0  1  2]
 [-1  0  1]
 [-2 -1  0]]
곱하기 : 
[[9 6 3]
 [6 4 2]
 [3 2 1]]
나누기 : 
[[1.         1.5        3.        ]
 [0.66666667 1.         2.        ]
 [0.33333333 0.5        1.        ]]


## III. Numpy로 선형대수 지식 끼얹기

### A. basics

### 0벡터 (0행렬)

원소가 모두 0인 벡터(행렬) -> `np.zeros(dim)`으로 생성. dim은 값 or tuple

In [33]:
# np.zeros(3,3) ## ERROR!
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 1벡터 (1행렬)
원소가 모두 1인 벡터(행렬) -> `np.ones(dim)` -> np.zeros와 사용법이 같다.

In [34]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

### 대각행렬(diagonal Matrix)
main digonal을 제외한 성분이 0인 행렬.`np.diag(main_diagonal)`으로 생성  
main_diagonal 값을 튜플로 전달

In [35]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [36]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### 항등행렬 (Identity Matrix)
main diagonal이 1인 대각행렬 -> `np.eye(n,dtype)`를 사용 (nxn matrix, dtype default는 float)

In [37]:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [38]:
np.eye(3,dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 행렬곱 (dot product)
행렬의 곱연산 -> `np.dot()` or `@` 연산 사용  
**행렬곱의 주의사항** : 앞 행렬의 **열의수**와 뒷행렬의 **행의수**가 같아야 한다!

In [40]:
mat_1 = np.array([[1,4],[2,3]])
mat_2 = np.array([[7,9],[0,6]])

print(mat_1.dot(mat_2))

print(mat_1@mat_2)

[[ 7 33]
 [14 36]]
[[ 7 33]
 [14 36]]


### B. furthermore

### 트레이스(trace)
main diagonal의 합. `np.trace()`사용

In [42]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.trace()

15

In [43]:
np.eye(3,dtype=int).trace()

3

### 행렬식 (determinant)
선형변환에서 vector의 scaling 척도  
`np.linalg.det()`로 계산.

* det() = 0 의 의미? == full rank가 아니다.

In [47]:
arr2 = np.array([[2,3],[1,6]])

np.linalg.det(arr2)

9.000000000000002

In [48]:
arr3 = np.array([[1,4,7],[2,5,8],[3,6,9]])

np.linalg.det(arr3)

0.0

### 역행렬 (Inverse Matrix)
행렬 A에 대해서 AB = BA = I 를만족하는 행렬 B = A^-1  
`np.linalg.inv()`로 계산

In [51]:
mat = np.array([[1,4],[2,3]])
mat_inv = np.linalg.inv(mat)

print(mat)
print(mat_inv)
print(mat.dot(mat_inv))

[[1 4]
 [2 3]]
[[-0.6  0.8]
 [ 0.4 -0.2]]
[[1. 0.]
 [0. 1.]]


### 고유값과 고유벡터 (eigenvalue, eigenvector)
정방 행렬(nxn)에 대해서 Ax = $\lambda$x를 만족하는 $\lambda$와 x를 각각 고유값, 고유벡터라 한다  
`np.linalg.eig()`로 구현

In [55]:
mat = np.array([[2,0,-2],[1,1,-2],[0,0,1]])

eig_val, eig_vec = np.linalg.eig(mat) # eigenvalue와 eigenvector순으로 출력
print(eig_val)
print(eig_vec)

[1. 2. 1.]
[[0.         0.70710678 0.89442719]
 [1.         0.70710678 0.        ]
 [0.         0.         0.4472136 ]]


In [57]:
mat.dot(eig_vec[:, 0])

array([0., 1., 0.])

In [58]:
eig_val[0] * eig_vec[:,0] # lambda x

array([0., 1., 0.])

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [64]:
def get_L2_norm(array):
    number = sum(list(map(sum,array*array)))
    return number

arr = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(get_L2_norm(arr))

42


### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [ ]:
def is_singular(array):
    return np.linalg.det(array)==0

arr = np.array([[1,2],[3,4]])
print(is_s)