# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

In [1]:
import numpy as np
arr = np.array([1,2,3])

arr

array([1, 2, 3])

In [2]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr.shape

(3,)

In [4]:
arr_2d.shape

(3, 3)

## II. Numpy로 연산하기

### Vector와 Scalar 사이의 연산
벡터외각 원소에 대해서 연산을 진행

In [11]:
x = np.array([1,2,3])
c = 5

print("더하기 : {}".format(x + c))
print("빼기 : {}".format(x-c))
print("곱하기 : {}".format(x*c))
print("나누기 : {}".format(x/c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산

벡터의 **같은 인덱스**끼리 연산이 진행!

In [12]:
y = np.array([1,3,5])
z = np.array([2,9,20])

print("더하기 : {}".format(y + z))
print("빼기 : {}".format(y-z))
print("곱하기 : {}".format(y*z))
print("나누기 : {}".format(y/z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


### Array Indexing
Python의 리스트와 유사하게 진행

In [13]:
W = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

W[0,0]

1

In [14]:
W[2,3]

12

In [15]:
W[1,2]

7

### Array Slicing

Python의 리스트와 유사하게 진행

In [20]:
W = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 2,3 -> W[0][1] , W[0][2]
# 6,7 -> W[1][1] , W[1][2]

W[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [21]:
W[0:2, 0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
W[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
W[0:3, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [25]:
W[:, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

### Array의 Broadcasting

기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능
하지만 만약에 피연산자가 연산 가능하도록 변환이 된다면 연산가능
이를 **broadcasting**이라고 함

### 1. M by N, M by 1

In [36]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

x = np.array([0,1,0])

x = x[:, None] # 전치됨
print(x)
print(a + x)

[[0]
 [1]
 [0]]
[[1 2 3]
 [5 6 7]
 [7 8 9]]


### M by N, 1 by N

In [33]:
y = np.array([0,1,-1])

print(a*y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


### M by 1, 1 by N

In [37]:
t = np.array([1,2,3])
t = t[:,None]
u = np.array([2,0,-2])
print(t + u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


## III. Numpy로 선형대수 지식 끼얹기

### A.basics

### 영벡터(행렬)

- 원소가 모두 0인 벡터(행렬)
- 'np.zeros(dim)'을 통해 생성, dim은 값, 혹은 튜플(, )

In [46]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 일행렬

- 원소가 모두 1일 벡터(행렬)
- 'np.ones(dim)'을 통해 생성, dim은 값,튜플(, )

In [47]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### 대각행렬
- Main diagonal을 제외한 성분이 0인 행렬
- 'np.diag(main_diagonal)'을 통해 생성

In [48]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [49]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### 항등행렬
- Main diagonal이 1인 대각행렬
- 'np.eye(n, (dtype))'를 사용

In [51]:
np.eye(2).dtype

dtype('float64')

In [53]:
np.eye(2) # float 이다.

array([[1., 0.],
       [0., 1.]])

In [55]:
np.eye(2, dtype=int) # 정수로 된다

array([[1, 0],
       [0, 1]])

### 행렬곱
- 행렬간의 곱연산
- np.dot() or @ 사용

In [56]:
mat_1 = np.array([[1,4],[2,3]])
mat_2 = np.array([[7,9],[0,6]])

mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

In [57]:
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

### B.Furthermore

### 트레이스(trace)
- 대각선의 합
- np.trace()를 사용

In [59]:
np.eye(10, dtype=int).trace()

10

In [60]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.trace()

15

### 행렬식(determinant)

- 행렬을 대표하는 값들 중 하나
- np.linalg.det() 으로 계산

In [62]:
arr_3 = np.array([[1,4,7],[2,5,8],[3,6,9]])

arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [63]:
np.linalg.det(arr_3)

0.0

In [66]:
np.linalg.det(mat_2)

41.999999999999986

### 역행렬

- 행렬 A에 대하여 AB = BA = I 를 만족하는 행렬 B = A^-1
- np.linalg.inv()으로 계산

In [67]:
mat = np.array([[1,4],[2,3]])
mat

array([[1, 4],
       [2, 3]])

In [69]:
mat_inv = np.linalg.inv(mat)

In [70]:
mat @ mat_inv

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

### 고유값과 고유벡터 (eigenvalue and eigenvector)

- 정방행렬 A에 대해 Ax = (\lambda)x 를 만족하는 상수 (\lambda)와 이에 대응하는 벡터
- np.linalg.eig() 으로 계산

In [71]:
mat = np.array([[2,0,-2],[1,1,-2],[0,0,1]])

mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [72]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

##### Validation

In [73]:
eig_val, eig_vec = np.linalg.eig(mat)

eig_val

array([1., 2., 1.])

In [74]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [76]:
mat @ eig_vec[:,0]

array([0., 1., 0.])

In [77]:
eig_val[0] * eig_vec[:, 0] # (lambda)x

array([0., 1., 0.])

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [94]:
def get_L2_norm(A):
    answer = sum(A*A)
    return np.sqrt(answer)

In [96]:
get_L2_norm(np.array([3,4]))

5.0

### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [101]:
def is_singular(A):
    return np.linalg.det(A) == 0

In [104]:
a = np.array([[1,3],[1,2]])
is_singular(a)


False