# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

### import numpy하기

In [2]:
import numpy as np

### numpy.array

numpy의 Container, array

In [3]:
arr = np.array([1,2,3,4])

arr

array([1, 2, 3, 4])

In [4]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr.shape

(4,)

In [6]:
np.shape(arr_2d) # arr_2d.shape

(3, 3)

In [7]:
arr.reshape((2,2))

array([[1, 2],
       [3, 4]])

In [8]:
arr.reshape((-1,1))
# -1 값은 남은 차원으로 부터 추정해서 알아서 들어감. -> arr.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [9]:
np.arange(2*3*5).reshape((2,3,5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

## II. Numpy로 연산하기

### Vector와 Scalar 사이의 연산

벡터의 각 원소에 대해서 연산을 진행

$x = \left(\begin{matrix} 1\\ 2 \\ 3 \end{matrix} \right) \quad c = 5$

In [10]:
x = np.array([1,2,3])
c = 5

print("덧셈 : {}",format(x+c))
print("뺄셈 : {}",format(x-c))
print("곱셈 : {}",format(x*c))
print("나눗셈 : {}",format(x/c))

덧셈 : {} [6 7 8]
뺄셈 : {} [-4 -3 -2]
곱셈 : {} [ 5 10 15]
나눗셈 : {} [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산

벡터의 **같은 인덱스**끼리 연산이 진행

$y = \left(\begin{matrix} 1 & 3 \ 5 \end{matrix} \right) \quad z = \left(\begin{matrix} 2\\ 9 \\ 20 \end{matrix} \right)$

In [11]:
y = np.array([1,3,5])
z = np.array([2,9,20])

print("덧셈 : {}",format(y+z))
print("뺄셈 : {}",format(y-z))
print("곱셈 : {}",format(y*z))
print("나눗셈 : {}",format(y/z))

덧셈 : {} [ 3 12 25]
뺄셈 : {} [ -1  -6 -15]
곱셈 : {} [  2  27 100]
나눗셈 : {} [0.5        0.33333333 0.25      ]


## Array Indexing

Python 리스트와 유사하게 진행

$w = \left(\begin{matrix} 1 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8 \\ 9 & 10 & 11 & 12  \end{matrix} \right)$

In [12]:
w = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

w[0,0]

1

In [13]:
w[2,3] == w[2,-1] # 12

True

## Array Slicing

Python 리스트와 유사하게 진행

In [14]:
w = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 2,3 -> 행 : 인덱스 0~1  ->  [0:2] 
# 6,7 -> 열 : 인덱스 1~2  ->  [1:3]

w[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [15]:
w[:2,:]  # w[0:2] , w[0:2, 0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
w[-1]

array([ 9, 10, 11, 12])

In [17]:
w[:,-1]

array([ 4,  8, 12])

## Array의 Broadcasting

기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능  
But 만약 피연산자가 연산 가능하도록 변환이 가능하다면 서로 다른 차원의 연산이 가능합니다.  
이를 **Broadcasting**이라고 합니다.

### 1. $M \times N, M \times 1$

$\left(\begin{matrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{matrix} \right) + \left(\begin{matrix} 0 \\ 1 \\ 0 \end{matrix} \right) \quad \rightarrow \quad \left(\begin{matrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{matrix} \right) + \left(\begin{matrix} 0 & 0 & 0 \\ 1 & 1 & 1 \\ 0 & 0 & 0 \end{matrix} \right) $

In [31]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0,1,0])

print(x)
x = x[:,None] # 행벡터 -> 열벡터로 전치, 슬라이스로 1차원배열을 2차원으로
print(x)
print(a+x)

[0 1 0]
[[0]
 [1]
 [0]]
[[1 2 3]
 [5 6 7]
 [7 8 9]]


### 2. $M \times N, 1 \times N$

$\left(\begin{matrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{matrix} \right) \times \left(\begin{matrix} 0 & 1 & -1 \end{matrix} \right) \quad \rightarrow \quad \left(\begin{matrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{matrix} \right) \times \left(\begin{matrix} 0 & 1 & -1 \\ 0 & 1 & -1 \\ 0 & 1 & -1 \end{matrix} \right) $

In [32]:
y = np.array([0,1,-1])

print(a*y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


### 3. $M \times 1, 1 \times N$

$\left(\begin{matrix} 1 & 1 & 1 \\ 2 & 2 & 2 \\ 3 & 3 & 3 \end{matrix} \right) + \left(\begin{matrix} 2 & 0 & -2 \\ 2 & 0 & -2 \\ 2 & 0 & -2 \end{matrix} \right)$

In [43]:
t = np.array([1,2,3]) 
t = t[:,None] # 행벡터를 -> 열벡터로 전치

u = np.array([2,0,-2])

print(t+u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


## III. Numpy로 선형대수 지식 끼얹기

### A. basics

### 영벡터(영행렬)

- 원소가 모두 0인 벡터(행렬)
- `np.zeros(dim)`을 통해 생성, dim은 값, 혹은 튜플 (,)

$\left(\begin{matrix} 0 & 0 & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{matrix} \right)$

In [2]:
import numpy as np

np.zeros(3)

array([0., 0., 0.])

In [5]:
np.zeros((3,3,3))  #인자는 2차원이상은 튜플로 묶어서 넣어야된다!

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### 일벡터(일행렬)

- 원소가 모두 1인 벡터(행렬)
- `np.ones(dim)`을 통해 생성, dim은 값, 튜플(,)

$\left(\begin{matrix} 1 & 1 & 1 \\ 1 & 1 & 1 \\ 1 & 1 & 1 \end{matrix} \right)$

In [7]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones([3,3])  # list 자료형도 되네?

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 대각행렬(Diagonal Matrix)

- Main Diagonal을 제외한 성분이 0인 행렬
- `np.diag((main_diagonals))`을 통해 생성할 수 있음.

$\left(\begin{matrix} 1 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 3 \end{matrix} \right)$

In [16]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [22]:
np.diag((2,4,5))

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

### 항등행렬(Identity Matrix)

- Main Diagonal이 1인 diagonal matrix(대각 행렬)
- `np.eye(n, (dtype=int,uint,float,complex,...))`을 통해 nxn 항등행렬을 생성할 수 있음.

$\left(\begin{matrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{matrix} \right)$

In [27]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [28]:
np.eye(3, dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 행렬곱(dot product)

- 행렬간에 정의되는 곱 연산
- `np.dot()` , `@`을 사용

In [36]:
mat_1 = np.array([[1,4],[2,3]])
mat_2 = np.array([[7,9],[0,6]])

In [51]:
print(mat_1.dot(mat_2))
print("--------")
print(np.dot(mat_1,mat_2))

[[ 7 33]
 [14 36]]
--------
[[ 7 33]
 [14 36]]


In [40]:
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

#### 행렬곱 `dot` vs `matmul`

- 2차원 행렬까지의 곱은 동일한 결과를 보여준다.
- 3차원 이상의 행렬(3-텐서)끼리 곱할 때는 다른 결과가 나온다.

In [3]:
A = np.arange(2*3*4).reshape((2,3,4))
B = np.arange(2*3*4).reshape((2,4,3))

#print(A)
#print("----------")
#print(B)

print("dot 함수 :",np.dot(A,B).shape)
print("-----------------------------------")
print("matmul 함수 : ",np.matmul(A,B).shape)

dot 함수 : (2, 3, 2, 3)
-----------------------------------
matmul 함수 :  (2, 3, 3)


### B. Linear Algebra

### 트레이스(trace)

- Main Diagonal의 Sum
- `np.trace()`을 사용

In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr.trace()

15

In [32]:
temp = np.arange(4*3).reshape((4,3))
print(temp)
print(temp.trace())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
12


In [33]:
np.eye(2,dtype=int).trace()

2

### 행렬식

- 행렬을 대표하는 값 중 하나
- 선형변환 과정에서 Vector의 Scaling 척도
- `np.linalg.det()`으로 계산

In [36]:
arr_2 = np.array([[2,3],[1,6]])

arr_2

array([[2, 3],
       [1, 6]])

In [37]:
np.linalg.det(arr_2)

9.000000000000002

In [26]:
arr_3 = np.array([[1,4,7],[2,5,8],[3,6,9]])

arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [27]:
np.linalg.det(arr_3) # 0의 의미는 singular하다. -> 역행렬이 없다.

0.0

### 역행렬(Inverse Matrix)

- 행렬 A에 대해서 $AA^{-1} = A^{-1}A = I$를 만족하는 행렬 $A^{-1}$
- `np.linalg.inv()`를 사용

In [41]:
mat = np.array([[1,4],[2,3]])

mat

array([[1, 4],
       [2, 3]])

In [44]:
mat_inv = np.linalg.inv(mat)

mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [47]:
mat @ mat_inv == np.eye(2) # I 항등행렬과 거의 비슷하다

array([[ True,  True],
       [False,  True]])

In [61]:
mat_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

mat_2
#np.linalg.inv(mat_2)  -> Error
# 역행렬이 존재하지 않을 경우 inv는 에러

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
mat_2 = np.array([[8,1,2],[5,7,7],[1,2,8]])

mat_2_inv = np.linalg.inv(mat_2)
mat_2_inv

array([[ 0.13592233, -0.01294498, -0.02265372],
       [-0.10679612,  0.20064725, -0.14886731],
       [ 0.00970874, -0.04854369,  0.16504854]])

### 고유값과 고유벡터 (eigenvalue and eigenvector)

- 정방행렬(nxn) A에 대해서 $Ax = \lambda x$를 만족하는 $\lambda$와 $x$를 각각 고유값과 고유벡터라 한다.
- `np.linalg.eig()`로 계산

In [62]:
mat = np.array([[2,0,-2],[1,1,-2],[0,0,1]])

mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [64]:
np.linalg.eig(mat) # 고유값, 고유벡터를 반환하는데 고유벡터는 칼럼 기준으로 봄

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

#### Validation

In [69]:
eig_val, eig_vec = np.linalg.eig(mat)

print("고유값 : ",eig_val)
print("고유벡터\n",eig_vec)

고유값 :  [1. 2. 1.]
고유벡터
 [[0.         0.70710678 0.89442719]
 [1.         0.70710678 0.        ]
 [0.         0.         0.4472136 ]]


In [72]:
mat @ eig_vec[:,0] # Ax

array([0., 1., 0.])

In [75]:
eig_val[0] * eig_vec[:, 0] # (lambda)x
# 행렬곱이 아니므로 그냥 스칼라 곱으로 Broadcasting

array([0., 1., 0.])

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [24]:
import numpy as np
from numpy import linalg as LA

def get_L2_norm(vec):
    return LA.norm(vec,ord = 2)

x = np.arange(1*5)+1
print("x =",x)
print("x의 L2 Norm :",get_L2_norm(x))

x = [1 2 3 4 5]
x의 L2 Norm : 7.416198487095663


### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [19]:
import numpy as np
from numpy import linalg as LA

def is_singular(mat):
    return LA.det(mat) == 0

y = (np.arange(3*3)+1).reshape((3,3))
print("y값\n",y)
print("is singular ?",is_singular(y))

y값
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
is singular ? True


----