# 1. 파이썬의 컴퓨팅 라이브러리, numpy
**numpy를 이용해서 데이터를 다뤄봅시다!**

### Our Goal
1. Numpy 시작하기
    - prerequisite : Python의 List
    - numpy import하기
    - numpy.array

2. Numpy로 연산하기
    - Vector - Scalar : elementwise! (+, -, *, /)
    - Vector - Vector : elementwise / broadcasting (+, -, *, /)
    - Indexing & Slicing
3. Example : Linear Algebra with Numpy
    1. basics
    - 영벡터 : `.zeros()`
    - 일벡터 : `.ones()`
    - 대각행렬 : `.diag()`
    - 항등행렬 : `.eye()`
    - 행렬곱 : `@` / `.dot()`
  
    2. furthermore
    - 트레이스 : `.trace()`
    - 행렬식 : `.linalg.det()`
    - 역행렬 : `.linalg.inv()`
    - 고유값 : `.linalg.eig()`


## I. Numpy 시작하기

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
print(arr.shape, arr_2d.shape)

(3,) (3, 3)


## II. Numpy로 연산하기
#### Vector와 Scalar 사이의 연산
벡터의각 원소에 대해서 연산을 진행

In [9]:
# 사칙연산
x = np.array([1,2,3])
c = 5
print(f'더하기 : {x+c}')
print(f'빼기 : {x-c}')
print(f'곱하기 : {x*c}')
print(f'나누기 : {x/c}')      

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


#### Vector와 Vector 사이의 연산
벡터와 같은 인덱스 끼리의 연산이 진행

In [10]:
y = np.array([1,3,5])
z = np.array([2,9,20])
print(f'더하기 : {y+z}')
print(f'빼기 : {y-z}')
print(f'곱하기 : {y*z}')
print(f'나누기 : {y/z}')   

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


#### Array의 indexing 및 slicing
List와 유사하게 진행, Array에서 특정 위치의 원소를 가지고 오기

In [12]:
w = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(w[1,2])
print(w[:2,1:3])

7
[[2 3]
 [6 7]]


In [15]:
#7의 값을 가져오려면??
w[1,2]

7

In [17]:
# 1행과 2행의 정보만 가져올 경우
w[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
# 3,4 열의 내용을 가져올 경우
w[:,2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

#### Array의 Broadcasting
- 기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능     
하지만 만약 피연산자가 연산 가능하도록 변한이 가능하면 연산가능
1. MxN , M x 1 의 형태일 경우 -> MxN의 형태로 나옴
2. MxN,  1 x N 의 형태일 경우 -> MxN의 형태로 나옴
3. Mx1 , 1 x N 의 형태일 경우 -> MxN의 형태로 나옴

1. M by N, M by 1

In [23]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = np.array([0,1,0])
x = x[:, None]    # 전치시키는 방법
print(a+x)

[[0]
 [1]
 [0]]
[[1 2 3]
 [5 6 7]
 [7 8 9]]


2. M by N , 1 by N

In [24]:
y = np.array([0,1,-1])
print(a * y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


3. M by 1, 1 by N 

In [25]:
t = np.array([1,2,3])
t = t[:,None]
u = np.array([2, 0, -2])
t + u

array([[ 3,  1, -1],
       [ 4,  2,  0],
       [ 5,  3,  1]])

## III. Numpy로 선형대수 지식 끼얹기

1.영행렬
- 원소가 모두 0인 행렬
- np.zeros(dim), dim은 값이거나 튜플 형태여야 함

In [30]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

2. 일행렬
- 원소가 모두 1인 행렬
- np.ones(dim)

In [31]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

3. 대각행렬
- 주 대각선을 제외한 성분이 0인 행렬
- np.diag(main_diagnal)

In [33]:
np.diag((2,4,4))

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 4]])

4.항등행렬
- 주 대각선이 1인 행렬
- np.eye(size ,dtype=int, float, uint, complex) 를 사용

In [37]:
np.eye(5,dtype= int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

5.행렬곱
- 행렬간의 곱 연산
- np.dot(), 또는 @ 사용

In [38]:
a = np.array([[1,4],[2,3]])
b = np.array([[7,5],[0,6]])
a.dot(b)

array([[ 7, 29],
       [14, 28]])

In [39]:
a @ b

array([[ 7, 29],
       [14, 28]])

6. 트레이스
- 주 대각선의 합
- np.trace()를 사용

In [40]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.trace(arr)

15

In [41]:
np.eye(5).trace()

5.0

7. 행렬식 (determinant)
- 선형변환에서 scaling 하는 척도
- np.linalg.det()로 계산

In [43]:
arr = np.array([[1,4,7],[2,5,8],[3,6,9]])
np.linalg.det(arr)

0.0

8. 역행렬
- 행렬 A에 대해 AB = BA = I 를 만족하는 행렬 B 
- np.linalg.inv() 로 계산

In [44]:
mat = np.array([[1,4],[2,3]])
mat

array([[1, 4],
       [2, 3]])

In [45]:
mat_inv = np.linalg.inv(mat)
mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [46]:
mat @ mat_inv

array([[1., 0.],
       [0., 1.]])

9. 고유값과 고유벡터 (eigenvalue and eigenvector)
- 정방행렬 A에 대해 $Ax = (\lambda)x$ 를 만족하는 상수와 이에 대응하는 벡터
- np.linalg.eig()로 계산

In [47]:
mat = np.array([[2,0,-2],[1,1,-2],[0,0,1]])
mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [49]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

In [50]:
eig_val , eig_vec = np.linalg.eig(mat)
eig_val

array([1., 2., 1.])

In [51]:
eig_vec

array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [52]:
mat @ eig_vec[:, 0]

array([0., 1., 0.])

In [54]:
eig_val[0] * eig_vec[:,0]

array([0., 1., 0.])

## IV. Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- **매개변수** : 1차원 벡터 (`np.array`)
- **반환값** : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [56]:
def get_L2_norm(arr):
    return np.sqrt(sum(arr ** 2))

arr = np.array([1,2,3,4,5])
print(get_L2_norm(arr))
    

7.416198487095663


### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()` 를 작성하세요

- 매개변수 : 2차원 벡터(`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환 

In [2]:
import numpy as np
def is_singular(arr):
    if not np.linalg.det(arr):
        return True
    else:
        return False
    
arr = np.array([[1,1],[2,2]])
print(is_singular(arr))
arr2 = np.array([[3,2],[4,7]])
print(is_singular(arr2))

True
False
