## 1. Numpy시작하기

### Remind : 리스트

In [3]:
arr = [1, 'two',3.0] #리스트의 치명적인 단점은 연산이 매우 느리다는 것

리스트의 치명적인 단점은 연산이 매우 느리다는 것

In [2]:
print(arr)

[1, 'two', 3.0]


### numpy 모듈 불러오기

In [2]:
import numpy as np

### 왜 numpy를 사용해야 할까요?

**List**

In [5]:
L = range(1000)

%timeit [i**2 for i in L]

493 µs ± 27.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


**numpy.array**

In [9]:
N = np.arange(1000)

%timeit N**2

1.83 µs ± 14.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### numpy.array

numpy의 Container, array

In [10]:
 arr = np.array([1,2,3])

In [11]:
arr

array([1, 2, 3])

In [12]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr.shape

(3,)

## Numpy로 연산하기

### vector와 Scalar 사이의 연산

벡터의 각 원소에 대해서 연산을 진행

In [4]:
import numpy as np
x= np.array([1,2,3])
#np.array([5])
c=5

In [7]:
# format 함수는 {} 에 인자를 채워주는 역할을 함
print("더하기 : {}".format(x+c))
print("뺴기 : {}".format(x-c))
print("곱하기 : {}".format(x*c))
print("나누기 : {}".format(x/c))


더하기 : [6 7 8]
뺴기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


### Vector와 Vector 사이의 연산

벡터의 **같은 인덱스**끼리 연산이 진행!

In [8]:
y=np.array([1,3,5]) #array의 인자는 하나이기에 반드시 묶어줘야함.
z=np.array([2,9,20])

In [9]:
print("더하기 : {}".format(y+z))
print("뺴기 : {}".format(y-z))
print("곱하기 : {}".format(y*z))
print("나누기 : {}".format(y/z))

더하기 : [ 3 12 25]
뺴기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


## Array의 Indexing

Array에서 특정 위치의 원하는 원소를 가져오고 싶다면?

**Python의 List와 유사하게 진행**

In [11]:
W = np.array([[1,2,3,4],
              [5,6,7,8],
             [9,10,11,12]]) # 3x4

W[0,0]

1

In [12]:
W[-1][-1]

12

In [14]:
#7을 가져오려면?
W[1][2]

7

## Array의 Slicing

Array에서 특정 범위의 원하는 원소들을 가지고 오고 싶다면?  
  
**Python의 List**와 유사하게 진행

In [18]:
W = np.array([[1,2,3,4],
              [5,6,7,8],
             [9,10,11,12]]) # 3x4

#2, 3, -> 행 : 인덱스 0~1 -> [0:2]
#6, 7, -> 열 : 인덱스 1~2 -> [1:3]
    
print(W[0:2,1:3]) #python의 List와는 다르게 []안에서 다 해결할 수 있음
print(W[0:2][1:3])

[[2 3]
 [6 7]]
[[5 6 7 8]]


In [19]:
W[0:2,0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
W[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
W[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
W[:,2:4]
#W[,2:4] 는 오류가 남.

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

## Array의 Broadcasting

Numpy가 연산을 진행하는 특수한 방법!  
1. **MxN, Mx1** : MxN과 Mx1을 연산할 땐 Mx1이 N번 열을 만들어서 broadcasting해서 계산함 ( 곱은 행렬곱이 아닌 기냥 연산곱)
2. **MxN, 1xN** : MxN과 1xN일 연산할 땐 1xN을 M번 행을 만들어서 broadcasting해서 계산함( 곱은 행렬곱이 아닌 기냥 연산곱)
3. **Mx1, 1xN** : M은 행, N은 열. 부족한 벡터가 얼마나 재생산되어야하는지 알수 없으므로 서로서로가 보안하는 구조로 broadcasting됨. 즉 M에선 N번 열을 늘려주고, N에서 M번 행을 늘려서 계산함

#### 1. M x N, M x1

In [38]:
# Mxn, Mx1
mxn = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
mx1=np.array([-1,0,1]) #행벡터

mx1=mx1[:,None] # 열벡터를 변환
print(mx1)

print(mxn+mx1)

[[-1]
 [ 0]
 [ 1]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


#### 2. M x N , 1 x N

In [39]:
onexn=np.array([0,1,-1])
print(mxn*onexn)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


#### 2. M x 1 , 1 x N

In [44]:
t = np.array([1,2,3]) #열벡터로 바꾸기~
t=t[:,None]
u = np.array([2,0,-2])
print(t,u)
"""
1 1 1    2 0 -2
2 2 2  + 2 0 -2
3 3 3    2 0 -2
"""

print(t+u)

[[1]
 [2]
 [3]] [ 2  0 -2]
[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


-------------

## 영벡터

- 원소가 모두 0인 벡터(행렬)
- `np.zeros(dim)`을 통해 생성, dim은 값, 혹은 튜플(,)형태여야함

In [46]:
np.zeros((3,3))
#np.zeros(3,3) : 오류남

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.zeros(2)

array([0., 0.])

In [49]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## 일벡터(일행렬)
- 원소가 모두 1인 벡터(행렬)
- `np.ones(dim)` 을 통해 생성, dim은 값, 튜플(,) 형태여야함

In [50]:
np.ones(2)

array([1., 1.])

In [52]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 대각행렬(diagonal matrix)
- main diagonal을 제외한 성분이 0인 행렬
- `np.diag(main_diagonal)`을 통해 생성 
  
   ex) `np.diag((2,4))`

In [53]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [54]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

## 항등행렬(identity matrix)
- Main diagonal이 1인 대각행렬
- `np.eye(n, dtype= int, uint, float, complex,...)`를 사용

In [62]:
# 기본적으로 nxn타입, dtype에는 int, float, complex, 등등
np.eye(2, dtype=int) 

array([[1, 0],
       [0, 1]])

In [64]:
np.eye(3,dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
np.eye(2) #기본 float 타입

array([[1., 0.],
       [0., 1.]])

## 행렬곱(dot product)
- 행렬간의 곱연산
- `np.dot()` or `@`사용

In [69]:
mat_1=np.array([[1,4],[2,3]])
mat_2=np.array([[7,9],[0,6]])

print(mat_1.dot(mat_2))
print(mat_1@mat_2)

[[ 7 33]
 [14 36]]
[[ 7 33]
 [14 36]]


In [68]:
mat_2.dot(mat_1)

array([[25, 55],
       [12, 18]])

In [70]:
mat_2@mat_1

array([[25, 55],
       [12, 18]])

---

## 트레이스(trace)
- Main diagonal의 합
- `np.trace()`를 사용

In [76]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(np.trace(arr)) # 1,5,9

print(np.trace(np.diag((1,5,9))))
np.diag((1,5,9))

15
15


array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

## 행렬식 (determinant)
- 행렬을 대표하는 값들 중 하나 => 선형변환
- 선형변환 과정에서 Vector의 Scaling 척도
- `np.linalg.det()`으로 계산

In [77]:
arr_2=np.array([[2,3],[1,6]])
arr_2

array([[2, 3],
       [1, 6]])

In [79]:
"""
2 3
1 6

2x6 - 3x1 : ad - bc

"""
np.linalg.det(arr_2)

9.000000000000002

In [81]:
arr_3=np.array([[1,4,7],
                [2,5,8],
                [3,6,9]])
arr_3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [82]:
"""
1 4 7
2 5 8
3 6 9

+1(5x9 - 6x8) -4(2x9 - 8x3) +7(2x6-5x3) = 0
0은 full rank가 아니다. 선형변환과정에서 차원의 손실이 일어난다.

"""
np.linalg.det(arr_3)

0.0

## 역행렬 (inverse matrix)
- 행렬 A에 대해 AB=BA=I를 만족하는 행렬 B=A^-1
- `np.linalg.inv()`으로 계산

In [83]:
mat = np.array([[1,4],[2,3]])
mat

array([[1, 4],
       [2, 3]])

In [85]:
mat_inv=np.linalg.inv(mat)
mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [86]:
mat@mat_inv

array([[1., 0.],
       [0., 1.]])

In [87]:
mat_inv@mat

array([[1., 0.],
       [0., 1.]])

## 고유값과 고유벡터(eigenvalue and eigenvector)
- Ax=(lambda)x를 만족시키는 람다값과 이에 대응하는 벡터
- 정방행렬 A(nxn)에 대해 $Ax=\lambda x$를 만족하는 상수(람다; $\lambda$)와 이에 대응하는 벡터
- `np.linalg.eig()`으로 계산

In [88]:
mat= np.array([[2,0,-2],
               [1,1,-2],
               [0,0,1]])
mat

array([[ 2,  0, -2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [94]:
#(람다, x)
""" x는 
* # @
* # @
* # @
식으로 열벡터임
"""
eig_val, eig_vec=np.linalg.eig(mat)

print(eig_val)
eig_vec

[1. 2. 1.]


array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]])

In [95]:
mat@ eig_vec[:,0] #Ax

array([0., 1., 0.])

In [96]:
eig_val[0] *eig_vec[:,0]

array([0., 1., 0.])

In [97]:
eig_vec[:,0]

array([0., 1., 0.])

In [1]:
eig_vec[:,1]

NameError: name 'eig_vec' is not defined

## Exercises

1. **어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 get_L2_norm()을 작성하세요**

 - **매개변수** : 1차원 벡터(`np.array`)
 - **반환값** : 인자로 주어진 벡터의 L2 Norm값(`number`)

2. **어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()`를 작성하세요**

  - **매개변수** : 2차원 벡터(`np.array`)
  - **반환값** : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환

In [13]:
import numpy as np

def get_L2_norm(vector_dim_1):
    return np.sqrt(np.sum(np.square(vector_dim_1)))

a=np.array([1,2,3])
get_L2_norm(a)

3.7416573867739413

In [14]:
#Singular matrix는 역이 존재하지 않는 matrix이다.
#ex) [[2,1],[4,2]] 란 A matrix가 존재할 때, 이것은 역은 존재하지 않는 행렬, 즉 sigular matrix가 된다.
# 이는 Ax=y일 때, y에 따라 해가 무수히 존재하거나(선형시스템 두개가 일치함), 해가 아예 없는 경우(선형시스템 두개가 평행) 이다.
import numpy as np

def is_singular(vector_dim_2):
    if np.linalg.det(vector_dim_2) == 0 : return True
    else : return False

a=np.array([[2,4],[4,8]])
print(is_singular(a))
b=np.array([[4,7],[2,4]])
print(is_singular(b))

True
False
