# Numpy로 연산하기


### Vector와 Scalar 사이의 연산

벡터의 각 원소에 대해 연산 진행

$$x = \begin{pmatrix}
{1} \\ {2} \\ {3}
\end{pmatrix}\quad c = 5$$

In [44]:
import numpy as np

In [45]:
x = np.array([1,2,3])
c = 5

print("더하기 : {}".format(x + c))
print("빼기 : {}".format(x - c))
print("곱하기 : {}".format(x * c))
print("나누기 : {}".format(x / c))

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


## Vector와 Vector 사이의 연산

벡터의 **같은 인덱스**끼리 연산 진행

$$y = \begin{pmatrix}
{1} \\ {3} \\ {5}
\end{pmatrix}\quad
z = \begin{pmatrix}
{2} \\ {9} \\ {20}
\end{pmatrix} $$

In [46]:
y = np.array([1,3,5])

z = np.array([2,9,20])

print("더하기 : {}".format(y + z))
print("빼기 : {}".format(y - z))
print("곱하기 : {}".format(y * z))
print("나누기 : {}".format(y / z))

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


## Array의 Indexing

Python의 List와 유사하게 진행

In [47]:
W = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(W[0,0]) # 1
print(W[2,3]) # 12

1
12


In [48]:
print(W[0:2, 1:3])

[[2 3]
 [6 7]]


In [49]:
# 결과 같음
print(W[0:2, 0:4]) 
print(W[:2, :4])
print(W[:2])

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [50]:
# 결과 같음
print(W[0:3, 2:4])
print(W[:, 2:4])

[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 3  4]
 [ 7  8]
 [11 12]]


## Array의 Broadcasting

기본적으로 같은 Type의 data에 대해서만 연산이 적용 가능
하지만 만약 피연산자가 연산 가능하도록 변환이 가능하다면 연산이 가능하다.
이를 **Broadcasting**이라고 한다.

### 1. M by N, M by 1

In [51]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

x = np.array([0,1,0])
x = x[:, None] # x를 전치

print(a+x)

[[1 2 3]
 [5 6 7]
 [7 8 9]]


### 2. M by N, 1 by N

In [52]:
y = np.array([0,1,-1])

print(a*y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


### 3. M by 1, 1 by N

In [53]:
t = np.array([1,2,3])
t = t[:, None] #t를 전치

u = np.array([2,0,-2])

print(t+u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


# Numpy로 선형대수 지식 끼얹기

## A. basics

### 영벡터(행렬)

- 원소가 모두 0인 벡터(행렬)
- `np.zeros(dim)`을 통해 생성, dim은 값, 혹은 튜플 (, )

In [54]:
# 오류 발생
np.zeros(3,3)

TypeError: data type not understood

In [55]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
print(np.zeros(1))
print(np.zeros(2))
print(np.zeros(3))

[0.]
[0. 0.]
[0. 0. 0.]


In [57]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### 일행렬

- 원소가 모두 1인 벡터(행렬)
- `np.ones(dim)` 을 통해 생성, dim은 값, 혹은 튜플(, )

In [58]:
np.ones(2)

array([1., 1.])

In [59]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 대각행렬

- Main diagonal을 제외하고 모두 0인 벡터(행렬)
- `np.diag((main_diagonal))` 을 통해 생성

In [60]:
np.diag((2,4))

array([[2, 0],
       [0, 4]])

In [61]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

### 항등행렬

- Main diagonal == 1인 대각행렬
- `np.eye(n, (dtype = int, uint, float, complex, ...))` 을 통해 생성

In [62]:
np.eye(2)
# default가 float type이다.

array([[1., 0.],
       [0., 1.]])

In [63]:
# 수를 int로 선언하기 위해선..?
np.eye(2, dtype = int)

array([[1, 0],
       [0, 1]])

In [64]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 행렬곱
- 행렬간의 곱연산
- `np.dot(), @` 를 사용

In [65]:
mat_1 = np.array([[1,4],[2,3]])
mat_2 = np.array([[7,9],[0,6]])

mat_1.dot(mat_2)

array([[ 7, 33],
       [14, 36]])

In [66]:
mat_1 @ mat_2

array([[ 7, 33],
       [14, 36]])

## B.Furthermore

### 트레이스

- Main Diagonal의 Sum
- `np.trace()` 를 사용

In [67]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [68]:
print(arr.trace()) # 1 + 5 + 9 = 15

15


In [69]:
print(np.eye(2,dtype=int))
print(np.eye(2, dtype = int).trace())

[[1 0]
 [0 1]]
2


### 행렬식

- 행렬을 대표하는 값 중 하나
- 선형변환 과정에서 Vector의 Scaling 척도
- `np.linalg.det()`으로 계산

In [70]:
arr_2 = np.array([[2,3],[1,6]])
print(arr_2)

[[2 3]
 [1 6]]


In [71]:
print(np.linalg.det(arr_2))

9.000000000000002


In [72]:
arr_3 = np.array([[1,4,7],[2,5,8],[3,6,9]])
print(arr_3)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [73]:
np.linalg.det(arr_3)

0.0

### 역행렬

- 행렬 A에 대해서 AB = BA = I를 만족하는 행렬 B
- `np.linalg.inv()` 사용

In [74]:
mat = np.array([[1,4],[2,3]])
print(mat)

[[1 4]
 [2 3]]


In [75]:
mat_inf = np.linalg.inv(mat)
print(mat_inf)

[[-0.6  0.8]
 [ 0.4 -0.2]]


In [76]:
mat@mat_inf #identity matrix가 나온다.

array([[1., 0.],
       [0., 1.]])

### 고유값과 고유벡터

- 정방행렬 (nxn) A에 대해 $Ax = \lambda x$을 만족하는 $\lambda$와 x를 각각 고유값과 고유벡터라 한다.

In [77]:
mat = np.array([[2,0,-2],[1,1,-2],[0,0,1]])
print(mat)

[[ 2  0 -2]
 [ 1  1 -2]
 [ 0  0  1]]


In [78]:
print(np.linalg.eig(mat)) 

(array([1., 2., 1.]), array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]]))


### validation

In [79]:
eig_val, eig_vec = np.linalg.eig(mat)
print(eig_val)
print(eig_vec)

[1. 2. 1.]
[[0.         0.70710678 0.89442719]
 [1.         0.70710678 0.        ]
 [0.         0.         0.4472136 ]]


In [80]:
mat @ eig_vec[:,0] #Ax

array([0., 1., 0.])

In [81]:
eig_val[0] * eig_vec[:, 0] #λx

array([0., 1., 0.])

## Exercises

### 1. 어떤 벡터가 주어졌을 때 L2 norm을 구하는 함수 `get_L2_norm()`을 작성하세요

- 매개변수 : 1차원 벡터 (`np.array`)
- 반환값 : 인자로 주어진 벡터의 L2 Norm값 (`number`)

In [82]:
def get_L2_norm(arr):
    return np.sqrt(sum(i**2 for i in arr))

In [83]:
arr_1 = [3,4]
print(get_L2_norm(arr_1))

arr_2 = [1,2,3,4,5]
print(get_L2_norm(arr_2))

5.0
7.416198487095663


### 2. 어떤 행렬이 singular matrix인지 확인하는 함수 `is_singular()`를 작성하세요

- 매개변수 : 2차원 벡터 (`np.array`)
- 반환값 : 인자로 주어진 벡터가 singular하면 True, non-singular하면 False를 반환

In [84]:
def is_singular(arr):
    if np.linalg.det(arr)==0:
        return True
    else:
        return False

In [85]:
# singluar matrix

singular_arr = np.array([[1,2],[1,2]])

print(is_singular(singular_arr))

# non-singluar matrix

non_singular_arr = np.array([[1,2],[3,2]])

print(is_singular(non_singular_arr))

True
False
