In [1]:
%matplotlib inline


What is PyTorch?
================

Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다:

-  NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
-  최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

Getting Started
---------------

Tensor는 NumPy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능합니다.



In [2]:
from __future__ import print_function
import torch

torch.__version__

'1.7.0+cu101'

초기화되지 않은 5x3 행렬을 생성합니다:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[3.2140e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.1553e-36]])


무작위로 초기화된 행렬을 생성합니다:



In [4]:
x = torch.randn(5, 3)
print(x)
x = torch.rand(5, 3)
print(x)

tensor([[ 0.4998, -0.0123,  1.2065],
        [ 0.4659, -1.1119, -1.0469],
        [ 0.3311,  0.5770, -0.9808],
        [-1.6933, -0.4311,  1.7591],
        [ 0.3346,  0.6398, -0.9855]])
tensor([[0.4225, 0.6696, 0.4458],
        [0.5661, 0.1570, 0.6661],
        [0.9700, 0.3892, 0.5740],
        [0.8643, 0.8190, 0.6379],
        [0.4663, 0.0164, 0.3621]])


dtype이 long이고 0으로 채워진 행렬을 생성합니다:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.ones(5, 3, dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


데이터로부터 tensor를 직접 생성합니다:



In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


또는 존재하는 tensor를 바탕으로 tensor를 만듭니다. 
이 메소드(method)들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(예. dtype)을 재사용합니다.


In [8]:
x = xe.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8039, -0.0473, -0.2606],
        [-0.6666, -0.2164,  1.5497],
        [-0.0673, -0.6175,  1.4867],
        [ 1.8226, -0.9508,  2.0158],
        [ 1.1701, -1.5394, -0.1466]])


행렬의 크기를 구합니다:



In [9]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])



덧셈: 문법1

In [10]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[-0.8039, -0.0473, -0.2606],
        [-0.6666, -0.2164,  1.5497],
        [-0.0673, -0.6175,  1.4867],
        [ 1.8226, -0.9508,  2.0158],
        [ 1.1701, -1.5394, -0.1466]])
tensor([[0.5261, 0.0257, 0.2226],
        [0.0479, 0.8267, 0.1479],
        [0.4942, 0.8873, 0.1607],
        [0.3858, 0.2859, 0.7855],
        [0.3595, 0.9427, 0.4000]])
tensor([[-0.2778, -0.0216, -0.0379],
        [-0.6187,  0.6103,  1.6975],
        [ 0.4269,  0.2698,  1.6474],
        [ 2.2084, -0.6649,  2.8013],
        [ 1.5296, -0.5966,  0.2534]])


덧셈: 문법2



In [11]:
print(torch.add(x, y))

tensor([[-0.2778, -0.0216, -0.0379],
        [-0.6187,  0.6103,  1.6975],
        [ 0.4269,  0.2698,  1.6474],
        [ 2.2084, -0.6649,  2.8013],
        [ 1.5296, -0.5966,  0.2534]])


덧셈: 결과 tensor를 인자로 제공


In [12]:
result = torch.empty(5, 3)
print(result)

torch.add(x, y, out=result)
print(result)

tensor([[ 3.2141e-36,  0.0000e+00,  1.5975e-43],
        [ 1.3873e-43,  1.4574e-43,  6.4460e-44],
        [ 1.4153e-43,  1.5274e-43,  1.5695e-43],
        [ 1.6255e-43,  1.6956e-43,  2.8013e+00],
        [ 1.5296e+00, -5.9664e-01,  2.5340e-01]])
tensor([[-0.2778, -0.0216, -0.0379],
        [-0.6187,  0.6103,  1.6975],
        [ 0.4269,  0.2698,  1.6474],
        [ 2.2084, -0.6649,  2.8013],
        [ 1.5296, -0.5966,  0.2534]])


덧셈: 바꿔치기(In-place) 방식


In [13]:
# adds x to y
print(y)
y.add_(x)
print(y)

tensor([[0.5261, 0.0257, 0.2226],
        [0.0479, 0.8267, 0.1479],
        [0.4942, 0.8873, 0.1607],
        [0.3858, 0.2859, 0.7855],
        [0.3595, 0.9427, 0.4000]])
tensor([[-0.2778, -0.0216, -0.0379],
        [-0.6187,  0.6103,  1.6975],
        [ 0.4269,  0.2698,  1.6474],
        [ 2.2084, -0.6649,  2.8013],
        [ 1.5296, -0.5966,  0.2534]])


<div class="alert alert-info"><h4>Note</h4><p>바꿔치기(In-place) 방식으로 tensor의 값을 변경하는 연산은 _ 를 접미사로 갖습니다.<p>
예: x.copy_(y), x.t_() 는 x 를 변경합니다.

<p>
NumPy스러운 인덱싱 표기 방법을 사용할 수도 있습니다!


In [14]:
print(x)
print(x[:, 1])

tensor([[-0.8039, -0.0473, -0.2606],
        [-0.6666, -0.2164,  1.5497],
        [-0.0673, -0.6175,  1.4867],
        [ 1.8226, -0.9508,  2.0158],
        [ 1.1701, -1.5394, -0.1466]])
tensor([-0.0473, -0.2164, -0.6175, -0.9508, -1.5394])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view 를 사용합니다:


In [15]:

x = torch.randn(4, 4)
print(x)

y = x.view(16)
z = y.view(-1, 2)  # the size -1 is inferred from other dimensions
print(y)
print(z)
print(y.size(), z.size())

tensor([[ 0.6260, -0.1789, -0.7456,  0.9438],
        [ 0.3400,  1.0393, -2.2191, -0.9922],
        [ 0.3981, -0.3946, -0.0845,  2.4196],
        [-1.1955,  0.0392,  0.4004,  0.2936]])
tensor([ 0.6260, -0.1789, -0.7456,  0.9438,  0.3400,  1.0393, -2.2191, -0.9922,
         0.3981, -0.3946, -0.0845,  2.4196, -1.1955,  0.0392,  0.4004,  0.2936])
tensor([[ 0.6260, -0.1789],
        [-0.7456,  0.9438],
        [ 0.3400,  1.0393],
        [-2.2191, -0.9922],
        [ 0.3981, -0.3946],
        [-0.0845,  2.4196],
        [-1.1955,  0.0392],
        [ 0.4004,  0.2936]])
torch.Size([16]) torch.Size([8, 2])


만약 tensor에 하나의 값만 존재한다면, .item() 을 사용하면 숫자 값을 얻을 수 있습니다.



In [16]:
x = torch.randn(1)
print(x)
print(type(x), type(x.item()))
print(x.item())


tensor([1.1069])
<class 'torch.Tensor'> <class 'float'>
1.10688054561615


**읽을 거리:**


  전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 난수(random number) 등과 같은 100가지 이상의 Tensor 연산은
  `여기 <http://pytorch.org/docs/torch>` 에 설명되어 있습니다.

NumPy 변환(Bridge)
------------

Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽습니다.

(CPU 상의) Torch Tensor와 NumPy 배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

- Torch Tensor를 NumPy 배열로 변환하기



In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


NumPy 배열의 값이 어떻게 변하는지 확인해보세요.



In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
temp = a.clone()
temp_numpy = temp.numpy()

a.add_(1)
print(a)
print(temp_numpy)

tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]


 - NumPy 배열을 Torch Tensor로 변환하기  
 
NumPy(np) 배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인해보세요.



In [21]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로의 변환을 지원하며, (NumPy에서 Tensor로의) 반대 변환도 지원합니다.

CUDA Tensors
------------

.to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있습니다.



In [22]:
import torch

# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.

x = torch.rand(4,4)
if torch.cuda.is_available():
    device = "cuda:0" # torch.device("cuda:0")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    print(y)


    x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[1.4512, 1.0800, 1.8194, 1.3981],
        [1.3423, 1.5176, 1.6927, 1.8044],
        [1.6748, 1.4634, 1.7604, 1.0744],
        [1.3394, 1.9641, 1.3050, 1.7403]], device='cuda:0')
tensor([[1.4512, 1.0800, 1.8194, 1.3981],
        [1.3423, 1.5176, 1.6927, 1.8044],
        [1.6748, 1.4634, 1.7604, 1.0744],
        [1.3394, 1.9641, 1.3050, 1.7403]], dtype=torch.float64)


In [23]:
x = x.cuda()